
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor y por las y por las convenciones              */
    /*   internacionales de  propiedad intelectual. Su uso no   */
    /*   autorizado dara  derecho a  COBISCORP para obtener     */
    /*   ordenes de  secuestro o retencion y  para perseguir    */
    /*   penalmente a los autores de cualquier infraccion.      */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/
    
    package  cobiscorp.ecobis.servicioclientes.service;
    import   cobiscorp.ecobis.clientesdto.dto.ClientesRequest;
    import   cobiscorp.ecobis.clientesdto.dto.ClientesResponse;
    import   cobiscorp.ecobis.clientesdto.dto.Message;
    import   cobiscorp.ecobis.clientesdto.dto.DatosClientes;
    
    import com.cobiscorp.cobis.cts.rest.client.api.exception.CTSRestException;
    import java.util.List;

    public interface IObtenerClientesService{
    
			//Have DTO
			public ClientesResponse obtenerClientesCobis(ClientesRequest inClientesRequest  )throws CTSRestException;
    }

  