---
openapi: 3.0.0
info:
  title: Get All Customer Questions
  description: Service to consult the security questions previously registered by the client.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/GetAllCustomerQuestions/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Get All Customer Questions
  description: Service to consult the security questions previously registered
paths:
  /apiOperations/questions/getAllCustomerQuestions:
    post:
      tags:
      - Get All Customer Questions
      summary: Get All Customer Questions
      operationId: getAllCustomerQuestions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestAllCustomerQuestions'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Get All Customer Questions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseAllCustomerQuestions'
      security:
      - bearerAuth: []
components:
  schemas:
    requestAllCustomerQuestions:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
    responseAllCustomerQuestions:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates whether the service was executed
          example: true
        cstmrQuestionsList:
          type: array
          items:
            $ref: '#/components/schemas/cstmrQuestions'
        cstmrAnswersList:
          type: array
          items:
            $ref: '#/components/schemas/cstmrAnswers'
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge
          example: success
    cstmrQuestions:
      type: object
      properties:
        id:
          maxLength: 10
          minLength: 1
          type: integer
          description: Question ID
          example: 1
        description:
          maxLength: 40
          minLength: 1
          type: string
          description: Question description
          example: ¿Cuál sería su vacación ideal?
        category:
          maxLength: 2
          minLength: 1
          type: string
          description: Question category
          example: RN
    cstmrAnswers:
      properties:
        questionId:
          maxLength: 10
          minLength: 1
          type: integer
          description: Question ID
          example: 1
        responseId:
          maxLength: 10
          minLength: 1
          type: integer
          description: Response ID
          example: 1
        description:
          maxLength: 40
          minLength: 1
          type: string
          description: Question description
          example: El Caribe
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
