---
openapi: 3.0.0
info:
  title: Customer Card Application
  description: This service is used for Customer Card Application
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/applicationRequestSave/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Customer Card Application
  description: This Service is used for Customer Card Application
paths:
  /apiOperations/customer/customerCardApplication:
    post:
      tags:
      - Customer Card Application API
      summary: Customer Card Application API
      operationId: customerCardApplication
      requestBody:
        description: Request Card Application
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardApplicationRequest'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response Create Customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardApplicationResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    CardApplicationRequest:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        accountNumber:
          maxLength: 15
          minLength: 11
          type: string
          description: Savings account number
          example: "402653207"
    CardApplicationResponse:
      properties:
        cardId:
          maxLength: 10
          minLength: 1
          type: integer
          description: Card Id
          example: 512
        cardNumber:
          maxLength: 20
          minLength: 1
          type: string
          description: Card Number
          example: 543924-XXXXXX-5618
        customerName:
          maxLength: 60
          minLength: 1
          type: string
          description: Customer Name
          example: JOSE CARLOS OLMOS SOLIS
        cardApplication:
          maxLength: 60
          minLength: 1
          type: integer
          description: Card application id
          example: 568
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
