---
openapi: 3.0.0
info:
  title: Activate Device
  description: Service to activate the customer's mobile device.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/deviceActivation/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: deviceActivation
  description: Service to activate the customer's mobile device.
paths:
  /apiOperations/enrollment/deviceActivation:
    post:
      tags:
      - deviceActivation
      summary: Activate Device
      operationId: deviceActivation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestDeviceActivation'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response deviceActivation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDeviceActivation'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestDeviceActivation:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        phoneNumber:
          maxLength: 10
          type: string
          description: Customer phone number
          example: "525568576731"
        aliasDevice:
          maxLength: 20
          type: string
          description: Nick name device
          example: android22
    ResponseDeviceActivation:
      type: object
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Indicates whether the service was executed.
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
