---
openapi: 3.0.0
info:
  title: Registration Of Third Parties Spei
  description: Service to Registration Of Third Parties Spei
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/registrationOfThirdPartiesSpei/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Register Account
  description: Service to Registration Of Third Parties Spei
paths:
  /apiOperations/accounts/registerAccount:
    post:
      tags:
      - Register Account
      summary: Registration Of Third Parties Spei
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestRegThirdSpei'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response registerAccount
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseRegThirdSpei'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestRegThirdSpei:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        phoneNumber:
          maxLength: 13
          type: string
          description: Customer phone number
          example: "525568576732"
        productOwner:
          maxLength: 30
          type: string
          description: Product Owner
          example: mi cuenta Trafalgar
        productAlias:
          maxLength: 40
          type: string
          description: Savings account number Alias
          example: Carlos Olmos
        Productid:
          maxLength: 10
          type: string
          description: Product ID.
          example: "10"
        productNumber:
          maxLength: 20
          type: string
          description: Savings account number
          example: "5568576731"
        productOwnerLastName:
          maxLength: 20
          type: string
          description: Savings account last name
          example: ""
        productOwnerSecLastName:
          maxLength: 20
          type: string
          description: Savings account second last name
          example: ""
        productOwnerCurp:
          maxLength: 20
          type: string
          description: Savings account curp
          example: ""
        productOwnerMail:
          maxLength: 40
          type: string
          description: Savings account email
          example: ""
        currencyId:
          maxLength: 10
          type: string
          description: Currency ID. 0 for MXN
          example: "0"
        channelId:
          maxLength: 10
          type: string
          description: Chanel ID
          example: "8"
        typeDestinationId:
          maxLength: 10
          type: string
          description: type destination ID
          example: "0"
        typeIdDestination:
          maxLength: 10
          type: string
          description: type ID destination
          example: A
        productOwnerId:
          maxLength: 10
          type: string
          description: Product owner ID
          example: ""
        localBankId:
          maxLength: 10
          type: string
          description: Local banck ID
          example: "40012"
    ResponseRegThirdSpei:
      type: object
      properties:
        success:
          maxLength: 50
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
