---
openapi: 3.0.0
info:
  title: Activate Debit Card
  description: Activate Debit Card Customer
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/activateDebitCardInit/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Activate Debit Card Customer
  description: This Service is used for activate debits card customer
paths:
  /apiOperations/customer/activateDebitCard:
    post:
      tags:
      - activateDebitCard API
      summary: Activate Debit Card Customer API
      operationId: activateDebitCard
      requestBody:
        description: Request Activate Card
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateDebitCardRequest'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response Create Customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivateDebitCardResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    ActivateDebitCardRequest:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        cardNumber:
          maximum: 22
          minLength: 10
          type: string
          description: Card number
          example: 543924-786577-7147
    ActivateDebitCardResponse:
      properties:
        accountNumber:
          maximum: 20
          minLength: 10
          type: string
          description: Saving account number
          example: "402653207"
        cardNip:
          maximum: 4
          minLength: 4
          type: string
          description: Debit card nip
          example: "7849"
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
