openapi: 3.0.0 
info:
  version: 1.0.0
  title: Account Debit Operation
  description: Account Debit Operation
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/APICobisCorp2023/accountDebitOperation/1.0.0
- description: Development Server  
  url: https://servicesapi.devcobistopaz.com/CWCREST/services/resources/cobis/api/Walmart/ServiceContractOperations
- description: Staging Server  
  url: https://servicesapi.stgcobis.com/CWCREST/services/resources/cobis/api/Walmart/ServiceContractOperations
- description: Pre-Production Server
  url: https://servicesapi.preprodcobis.com/CWCREST/services/resources/cobis/api/Walmart/ServiceContractOperations
  
tags:
- name: debitOperation
  description:  Service to apply debit account
paths:
  /apiOperations/accounts/debitOperation:
    post:
      security:
        - OAuth2_Development: []
        - OAuth2_Staging: []
        - OAuth2_PreProd: []
      tags:
      - debitOperation
      summary: Service to apply debit account
      operationId: debitOperation
      parameters:
      - name: x-request-id
        in: header
        description: Request identifier (uuid)
        required: true
        style: simple
        explode: false
        example: 'c44d6ddb-41c0-4315-9001-f72bd7122e84'
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DebitAccountRequest'
        required: true
      responses:
        400:
          description: The data sent is incorrect or corrupted
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Error40012'
                  - $ref: '#/components/schemas/Error40080'
                  - $ref: '#/components/schemas/Error40081'
                  - $ref: '#/components/schemas/Error40082'
                  - $ref: '#/components/schemas/Error40092'
                  - $ref: '#/components/schemas/Error40106'
                  - $ref: '#/components/schemas/Error40104'
                  - $ref: '#/components/schemas/Error40107'
                  - $ref: '#/components/schemas/Error40108'
                  - $ref: '#/components/schemas/Error40124'
                  - $ref: '#/components/schemas/Error40124'
        500:
          description: An error occurred on the server
          content:
            application/json:
              schema:  
                oneOf:
                 - $ref: '#/components/schemas/Error50045'
                 - $ref: '#/components/schemas/Error50042'
                 - $ref: '#/components/schemas/Error50046'
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response debit operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebitAccountResponse'
components:
  securitySchemes:
      OAuth2_Staging:
        type: oauth2
        description:  This API uses OAuth 2 
        flows: 
          clientCredentials:
            tokenUrl: https://keycloak.stgcobis.com/realms/walmart/protocol/openid-connect/token
            refreshUrl: https://keycloak.stgcobis.com/realms/walmart/protocol/openid-connect/token
            scopes: {}       
      OAuth2_Development:
        type: oauth2
        description:  This API uses OAuth 2 
        flows: 
          clientCredentials:
            tokenUrl: https://keycloak.devcobistopaz.com/realms/walmart/protocol/openid-connect/token
            refreshUrl: https://keycloak.devcobistopaz.com/realms/walmart/protocol/openid-connect/token
            scopes: {} 
      OAuth2_PreProd:
        type: oauth2
        description: This API uses OAuth 2
        flows:
          clientCredentials:
            tokenUrl: 
              https://keycloak.preprodcobis.com/realms/walmart/protocol/openid-connect/token
            refreshUrl: 
              https://keycloak.preprodcobis.com/realms/walmart/protocol/openid-connect/token
            scopes: {}
        
  schemas:
    DebitAccountRequest:
      description: Input for debit operation
      type: object
      required: 
        [externalCustomerId,accountNumber,amount,referenceNumber, debitReason]
      properties:
        externalCustomerId:
            type: integer
            description: External Customer Id 
            minLength: 1
            maxLength: 12
            example: 4490   
        accountNumber:
          type: string 
          description: Account Number
          maxLength: 20
          example: "03000037941"
        amount:
          type: number 
          description: Amount to debit
          maxLength: 12
          minimum: 1
          example: 50
        referenceNumber:
          type: string 
          description: Reference Number 
          maxLength: 6
          example: "838383"
        debitReason:
          type: string
          description: Debit reason
          maxLength: 25
          example: Card delivery fee 
        originCode:
          type: integer
          description: |
            Code of the system of origin of the transaction:
            - 1 : App Cashi
            - 2 : CCA Cashi
            - 3 : Internet Banking Cashi
          maxLength: 1
          example: 1
          minimum: 1
        originMovementId:
          type: string
          description: Indicates the movement ID of the original transaction.
          maxLength: 25
          example: "123456"
        originReferenceNumber:
          type: string
          description: Indicates the reference number of the original transaction.
          maxLength: 25
          example: "123456"
    DebitAccountResponse:
      description: Output for debit operation
      type: object
      properties:
        success:
          type: boolean
          description: Indicates whether the service was executed.
          example: true
        movementId:
          type: string
          description: movement ID operation
          maxLength: 20
          example: 20463327 
        response:
          $ref: '#/components/schemas/Response'
          
    Response:
      type: object
      properties:
        code:
          type: integer
          maxLength: 10
          example: 0
          description: Result Code
        message:
          type: string
          maxLength: 500
          example: success
          description: Result Mesagge Code
          
    Error40012:
        description: Customer with externalCustomerId [id] does not exist
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40012
                description: code error
              message:
                type: string
                example: Customer with externalCustomerId [id] does not exist
                description: message error
    
    Error40080:
        description: accountNumber does not exist
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40080
                description: code error
              message:
                type: string
                example: accountNumber does not exist
                description: message error
              
    Error40081:
        description: The account number does not correspond to the customer id
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40081
                description: code error
              message:
                type: string
                example: The account number does not correspond to the customer id
                description: message error 
                
    Error40082:
        description: accountNumber must not be empty
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40082
                description: code error
              message:
                type: string
                example: accountNumber must not be empty
                description: message error
                
    Error40092:
        description: referenceNumber must not be empty
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40092
                description: code error
              message:
                type: string
                example: referenceNumber must not be empty
                description: message error
                
    Error40106:
        description: debitConcept must not be empty
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40106
                description: code error
              message:
                type: string
                example: debitConcept must not be empty
                description: message error
                
    Error40104:
        description: referenceNumber must have 6 digits
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40104
                description: code error
              message:
                type: string
                example: referenceNumber must have 6 digits
                description: message error
                
    Error50045:
        description: Error account debit operation
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  50045
                description: code error
              message:
                type: string
                example: Error account debit operation
                description: message error
                
    Error50042:
        description: The customer does not have an affiliation
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  50042
                description: code error
              message:
                type: string
                example: The customer does not have an affiliation
                description: message error
                
    Error40107:
        description: amount must be greater than 0
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40107
                description: code error
              message:
                type: string
                example: amount must be greater than 0
                description: message error
    
    Error40108:
        description: commission must be greater than or equal to 0
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40108
                description: code error
              message:
                type: string
                example: commission must be greater than or equal to 0
                description: message error
    
    Error40124:
      description: Debit reason not found
      type: object
      properties:
        success:
          type: boolean
          example: false
        response:
          type: object
          properties:
            code:
              type: integer
              example:  40124
              description: code error
            message:
              type: string
              example: Debit reason not found
              description: message error
    
    Error40125:
        description: Origin code not found
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  40125
                description: code error
              message:
                type: string
                example: Origin code not found
                description: message error
                
    Error50046:
        description: The balance is less than 0 with the amount entered
        type: object
        properties:
          success:
            type: boolean
            example: false
          response:
            type: object
            properties:
              code:
                type: integer
                example:  Error50046
                description: code error
              message:
                type: string
                example: The balance is less than 0 with the amount entered
                description: message error
    
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.