---
openapi: 3.0.0
info:
  title: Registration Of Third Parties Same Bank
  description: Service to Registration of third parties same bank
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/registrationOfThirdPartiesSameBank/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: RegisterAccount
  description: Service to Registration Of Third Parties Same Bank
paths:
  /apiOperations/accounts/registerAccount:
    post:
      tags:
      - RegisterAccount
      summary: Service to Registration Of Third Parties Same Bank
      operationId: registerAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestRegThirdBank'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response registerAccount
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseRegThirdBank'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestRegThirdBank:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        phoneNumber:
          maxLength: 13
          type: string
          description: Customer phone number
          example: "525568576731"
        productOwner:
          maxLength: 20
          type: string
          description: Product Owner
          example: same bank
        productAlias:
          maxLength: 40
          type: string
          description: Savings account number Alias
          example: GUSTAVO MARTINEZ BURGUETE
        Productid:
          maxLength: 10
          type: string
          description: Product ID.
          example: "4"
        productNumber:
          maxLength: 20
          type: string
          description: Savings account number
          example: "402665500"
        currencyId:
          maxLength: 10
          type: string
          description: Currency ID. 0 for MXN
          example: "0"
        channelId:
          maxLength: 10
          type: string
          description: Chanel ID
          example: "8"
        localBankId:
          maxLength: 10
          type: string
          description: Local banck ID
          example: "40012"
    ResponseRegThirdBank:
      type: object
      properties:
        success:
          maxLength: 40
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
