---
openapi: 3.0.1
info:
  title: Send Contract By Mail
  description: Service To Send Contract By Mail.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/sendContractByMail/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: SendContractByMail
  description: Service To Send Contract By Mail.
paths:
  /apiOperations/onbording/sendContractByMail:
    post:
      tags:
      - SendContractByMail
      summary: Send Contract By Mail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSendContrac'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response sendContractByMail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSendContrac'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestSendContrac:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        firstName:
          maxLength: 10
          type: string
          description: First name
          example: JOSE CARLOS
        middleName:
          maxLength: 20
          type: string
          description: Middle name
          example: ""
        lastname:
          maxLength: 20
          type: string
          description: Last name
          example: OLMOS SOLIS
        surname:
          maxLength: 20
          type: string
          description: Surname.
          example: SOLIS
        birthdate:
          maxLength: 20
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          type: string
          description: Birth date
          example: 1983-09-19
        gender:
          maxLength: 10
          type: string
          description: Gender
          example: M#MASCULINO
        validityDate:
          maxLength: 20
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          type: string
          description: Validity date
          example: 2052-09-19
        curp:
          maxLength: 20
          type: string
          description: Official document
          example: OOSC861001HMCLLT08
        email:
          maxLength: 40
          type: string
          description: Email
          example: j1106carloslibra@hotmail.com
        country:
          maxLength: 20
          type: string
          description: Country
          example: MEXICO
        province:
          maxLength: 20
          type: string
          description: Province
          example: CIUDAD DE MEXICO
        street:
          maxLength: 40
          type: string
          description: Street
          example: CALLESITA
        profession:
          maxLength: 20
          type: string
          description: Profession
          example: NOC
        economicActivity:
          maxLength: 20
          type: string
          description: Economic activity
          example: Construcción
        companyName:
          maxLength: 20
          type: string
          description: Company name
          example: JOSE CARLOS
        beneficiaries:
          maxLength: 20
          type: string
          description: Beneficiaries
          example: QNMEZ JEJEBJ;DIRECCILN;100
    ResponseSendContrac:
      type: object
      properties:
        success:
          maxLength: 40
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
