---
openapi: 3.0.0
info:
  title: Account Debit Operation
  description: Account Debit Operation
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/accountDebitOperation/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: accountDebitOperation
  description: Service to apply debit account
paths:
  /apiOperations/account/accountDebitOperation:
    post:
      tags:
      - accountDebitOperation
      summary: Service to apply debit account
      operationId: accountDebitOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DebitAccountRequest'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response transferSpi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebitAccountResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    DebitAccountRequest:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          minLength: 1
          type: integer
          description: External Customer Id
          example: 220
        accountDebit:
          maxLength: 20
          type: string
          description: Destination Account Number
          example: "5568576731"
        amount:
          minimum: 1
          maxLength: 12
          type: number
          description: Amount to debit
          example: 50
        description:
          maxLength: 100
          type: string
          description: Description
          example: Prueba
        ownerName:
          maxLength: 30
          type: string
          description: Owner Name
          example: Carlos
        detail:
          maxLength: 40
          type: string
          description: Detail
          example: Prueba
        commission:
          maxLength: 20
          type: number
          description: amount  commission
          example: 4.5
        latitude:
          maxLength: 40
          type: number
          description: Latitude
          example: 19.4050565
        longitude:
          maxLength: 40
          type: number
          description: Longitude
          example: -98.9077518
        referenceNumber:
          maxLength: 20
          type: string
          description: Reference Number
          example: "838383"
        debitConcept:
          maxLength: 50
          type: string
          description: debit concept
          example: Payment to acc
        originCode:
          minimum: 1
          maxLength: 12
          type: integer
          description: system origin
    DebitAccountResponse:
      type: object
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Indicates whether the service was executed.
          example: true
        referenceCode:
          maxLength: 20
          type: string
          description: Reference Code operation
          example: "20463327"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
