---
openapi: 3.0.0
info:
  title: Validate Debit Card Order
  description: Service to obtain the debit card associated with an existing savings account.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/validateDebitCardOrder/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Validate Debit Card Order
  description: This Service is used for validate debit card order customer
paths:
  /apiOperations/customer/validateDebitCardOrder:
    post:
      tags:
      - Validate Debit Card Order
      summary: Validate Debit Card Order Customer API
      operationId: validateDebitCardOrder
      requestBody:
        description: DebitCardOrderResponse
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DebitCardOrderRequest'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response Create Customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebitCardOrderResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    DebitCardOrderRequest:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        accountNumber:
          maxLength: 15
          minLength: 11
          type: string
          description: Savings account number
          example: "402653207"
    DebitCardOrderResponse:
      properties:
        customerName:
          maxLength: 60
          minLength: 1
          type: string
          description: Customer Name
          example: JOSE CARLOS OLMOS SOLIS
        minAmount:
          maxLength: 12
          minLength: 1
          type: number
          description: minLength amount for card
          example: 200
        hasSavingAccount:
          maxLength: 2
          minLength: 1
          type: boolean
          description: check if it have a savings account
          example: true
        SavingAccountLevel:
          maxLength: 3
          minLength: 1
          type: integer
          description: check if it have a savings account
          example: 3
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
