---
openapi: 3.0.0
info:
  title: Delete Beneficiary
  description: Service to delete a beneficiary.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/deleteBeneficiary/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: deleteBeneficiary
  description: Service to delete a beneficiary.
paths:
  /apiOperations/onbording/deleteBeneficiary:
    post:
      tags:
      - deleteBeneficiary
      summary: Service to  delete a beneficiary.
      operationId: deleteBeneficiary
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestDeleteBeneficiary'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response deleteBeneficiary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseDeleteBeneficiary'
      security:
      - bearerAuth: []
components:
  schemas:
    requestDeleteBeneficiary:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        beneficiaryId:
          maxLength: 12
          type: integer
          description: Beneficiary ID
          example: 1
    responseDeleteBeneficiary:
      type: object
      properties:
        success:
          maxLength: 40
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
