---
openapi: 3.0.1
info:
  title: Afiliate Customer
  description: Service To Afiliate Customer.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/affiliateCustomer/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: affiliateCustomer
  description: Service To Afiliate Customer.
paths:
  /apiOperations/onbording/affiliateCustomer:
    post:
      tags:
      - affiliateCustomer
      summary: Afiliate Customer
      operationId: affiliateCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAffiliateCustomer'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response affiliateCustomer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseAffiliateCustomer'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestAffiliateCustomer:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
    ResponseAffiliateCustomer:
      type: object
      properties:
        success:
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        userCreated:
          type: string
          description: Amount comission
          example: ncmcenf
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
