---
openapi: 3.0.1
info:
  title: Update Images
  description: Service to Update Images.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/updateImages/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: updateImages
  description: Service to Update Images.
paths:
  /apiOperations/onbording/updateImages:
    post:
      tags:
      - updateImages
      summary: Service to Update Images.
      operationId: updateImages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestUpdateImages'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response updateImages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUpdateImages'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestUpdateImages:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        documentId:
          maxLength: 15
          type: string
          description: Document ID
          example: "1"
        extension:
          maxLength: 8
          type: string
          description: Type Extension of document
          example: jpg
        imageDataBase64:
          type: string
          description: Document convert Base64
          example: /9j/4AAQSkZJRgABAQAAAQABAAD/4gIoSUNDX1BST0ZJTEUAAQEAA...
        tipoDocumento:
          maxLength: 8
          type: string
          description: Type of document
          example: INE
    ResponseUpdateImages:
      type: object
      properties:
        success:
          maxLength: 40
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
