---
openapi: 3.0.0
info:
  title: Update Customer Address
  description: Service update address customer
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/updateCustomerAddress/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Update Customer's
  description: This Service is used for Update Customer Address
paths:
  /apiOperations/customer/updateCustomerAddress:
    post:
      tags:
      - Update Customer's
      summary: Update customer addrerss
      operationId: createCustomer
      requestBody:
        description: Request to update customer address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerAddressRequest'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response Create Customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerAddressResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    UpdateCustomerAddressRequest:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        country:
          maximum: 10
          minimum: 1
          type: string
          description: Country of Residence ID(Use the "getCatalog" service with table cl_pais)
          example: "52"
        zipcode:
          maximum: 5
          minimum: 5
          type: string
          description: Zip code
          example: "10000"
        province:
          maximum: 2
          minimum: 1
          type: string
          description: Province ID, (Use the "getCatalog" service with table cl_pais)
          example: "9"
        city:
          maximum: 10
          minimum: 1
          type: string
          description: City of residence ID,for example 9011 (Use the "getCatalog" service with table cl_ciudad)
          example: "9011"
        subdivisioncode:
          maximum: 10
          minimum: 1
          type: string
          description: Id of colony or parish of residence,  (Use the "getCatalog" service with table cl_parroquia)
          example: "90111959"
        townCode:
          maximum: 6
          minimum: 1
          type: string
          description: Id of locality of residence (Use the service searchLocationCatalogwith City of residence ID)
          example: "146"
        street:
          maximum: 25
          minimum: 1
          type: string
          description: street name of the customer's home
          example: my street
        externalNumber:
          maximum: 10
          minimum: 1
          type: string
          description: External number of the customer's home
          example: "10"
        internalNumber:
          maximum: 5
          minimum: 1
          type: string
          description: Inside number of the customer's home  (NA is always 0 )
          example: "0"
        referenceAddress:
          maximum: 20
          minimum: 1
          type: string
          description: Reference Address
          example: street park
        timeCurrentRecide:
          maximum: 3
          minimum: 1
          type: string
          description: Customer time current residence
          example: "3"
        AddressTypeCode:
          maximum: 5
          minimum: 1
          type: string
          description: Customer type address (Use the "getCatalog" service with table cl_tdireccion)
          example: AE
        propertyTypeCode:
          maximum: 5
          minimum: 1
          type: string
          description: Type of provider where you live (Use the "getCatalog" service with table cl_tpropiedad)
          example: PRO
        anotherAddress:
          maximum: 15
          minimum: 1
          type: string
          description: Description of the other type of addres
          example: my type address
    UpdateCustomerAddressResponse:
      properties:
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
