---
openapi: 3.0.0
info:
  title: Search Zip Code
  description: Search Zip Code
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/searchZipCode/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Search Zip Code
  description: This Service is used for find zip code
paths:
  /onboarding/sarchZipCode:
    post:
      tags:
      - sarchZipCode API
      summary: Search Zip Code API
      operationId: sarchZipCode
      requestBody:
        description: Search Zip Code
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchZipCodeRequest'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response Create Customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchZipCodeResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    SearchZipCodeRequest:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        phoneNumber:
          maxLength: 13
          type: string
          description: Customer phone number
          example: "525568576731"
        zipCode:
          maxLength: 5
          minLength: 3
          type: string
          description: number zip code
          example: "13278"
    SearchZipCodeResponse:
      properties:
        codeColony:
          maxLength: 20
          minLength: 10
          type: string
          description: ColonyId (Use the "getCatalog" service with the cl_parroquia table to get the name)
          example: "90100001"
        cityCode:
          maxLength: 10
          minLength: 1
          type: string
          description: city code City or Municipality ID (Use the "getCatalog" service with the cl_ciudad table to get the name)
          example: "9010"
        provinceCode:
          maxLength: 2
          minLength: 1
          type: string
          description: code province Province or State ID (Use the "getCatalog" service with the cl_provincia table to get the name)
          example: "9"
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
