---
openapi: 3.0.0
info:
  title: Validate Identity
  description: Service to initiate the validation of a client's identity document. Interface with META provider
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/ValidateIdentity/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Validate Identity
  description: Service to initiate the validation of a client's identity document. Interface with META provider
paths:
  /apiOperations/onbording/sendImagesToMati:
    post:
      tags:
      - Validate Identity
      summary: Validate Identity
      operationId: validateIdentity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestValidateIdentity'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Validate identity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseValidateIdentity'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestValidateIdentity:
      properties:
        type:
          maxLength: 3
          minLength: 1
          type: string
          description: Type identity, like (INE, PAS, ,MIG)
          example: INE
        imageAnverso:
          type: string
          description: Base64 image of the front of the identity document
          example: /9j/4AAQM98ASkZJRgABAQANJM98AUDAQSkZJa9wJCAFW8I....
        imageReverso:
          type: string
          description: Base64 image of the back of the identity document
          example: /QAN9j/4AAQSkZJRgABAQANJM98AQSkZJAUDa9wJCAFW8I....
        imageDomicile:
          type: string
          description: Base64 image of proof of
          example: /JCAF9j/4AAQSkZJRgABAQSkZJAQANJM98AUDa9wJCAFW8I....
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
    ResponseValidateIdentity:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates whether the service was executed
          example: true
        numeroVerficacion:
          maxLength: 50
          type: string
          description: Process date
          example: Verification number of META/MATI
        nombreEvento:
          maxLength: 50
          type: string
          description: Name META/MATI event
          example: verification_completed
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  parameters:
    token:
      name: token
      in: header
      description: Authentication token
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
