---
openapi: 3.0.0
info:
  title: Update Profile
  description: Update Profile
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/updateProfile/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Update Profile
  description: Service to update profile
paths:
  /apiOperations/enrollment/updateProfile:
    post:
      tags:
      - Update Profile
      summary: Service to Update Profile
      operationId: updateProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestUpdateProfile'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUpdateProfile'
components:
  schemas:
    RequestUpdateProfile:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        email:
          maxLength: 40
          type: string
          description: Email
          example: j1106carloslibra@hotmail.com
        phoneNumber:
          maxLength: 10
          minLength: 1
          type: string
          description: Customer phone number
          example: "525568576731"
    ResponseUpdateProfile:
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
