---
openapi: 3.0.0
info:
  title: Municipality By State
  description: Service to obtain the identifier and name of the municipality corresponding to a zip code and state.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/getMunicipalityByState/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: getMunicipalityByState
  description: Service to obtain the identifier and name of the municipality corresponding to a zip code and state.
paths:
  /apiOperations/onbording/getMunicipalityByState:
    post:
      tags:
      - getMunicipalityByState
      summary: Municipality By State
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestMunicipalityByState'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response getMunicipalityByState
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMunicipalityByState'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestMunicipalityByState:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        zipCode:
          maxLength: 5
          type: string
          description: Zip code
          example: "512"
    ResponseMunicipalityByState:
      type: object
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Indicates whether the service was executed
          example: true
        addressTypeItems:
          type: array
          items:
            $ref: '#/components/schemas/ResponseMunicipalityByState_addressTypeItems'
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result message code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge
          example: success
    ResponseMunicipalityByState_addressTypeItems:
      properties:
        code:
          maxLength: 20
          type: string
          description: City or Municipality ID
          example: "9010"
        value:
          maxLength: 20
          type: string
          description: City or Municipality name
          example: Alvaro Obregón
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  parameters:
    token:
      name: token
      in: header
      description: Token de autenticacion en API.
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
