---
openapi: 3.0.0
info:
  title: Catalogue Of Locations
  description: Service to obtain the locality of a municipality or city.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/searchLocationCatalog/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: searchLocationCatalog
  description: Service to obtain the locality of a municipality or city.
paths:
  /apiOperations/onbording/searchLocationCatalog:
    post:
      tags:
      - searchLocationCatalog
      summary: Catalogue Of Locations
      operationId: searchLocationCatalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSearchLocationCatalog'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response searchLocationCatalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSearchLocationCatalog'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestSearchLocationCatalog:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        City:
          maxLength: 10
          type: string
          description: City or Municipality ID
          example: "9010"
    ResponseSearchLocationCatalog:
      type: object
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Indicates whether the service was executed.
          example: true
        message:
          $ref: '#/components/schemas/Message'
        addressTypeItem:
          type: array
          items:
            $ref: '#/components/schemas/ResponseSearchLocationCatalog_addressTypeItem'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
    ResponseSearchLocationCatalog_addressTypeItem:
      properties:
        code:
          maxLength: 20
          type: string
          description: Location ID
          example: "1"
        value:
          maxLength: 20
          type: string
          description: Location name
          example: ALVARO OBREGON
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
