---
openapi: 3.0.0
info:
  title: Encrypt Data
  description: Service for data encryption. Used to encrypt a client's password prior to login.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/EncryptData/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: EncryptData
  description: Encrypt Data Client
paths:
  /apiOperations/security/encryptData:
    post:
      tags:
      - EncryptData
      summary: Encrypt Data
      operationId: encryptData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestEncriptData'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response EncryptData
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEncriptData'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestEncriptData:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        password:
          maxLength: 200
          type: string
          description: Phrase or password to be encrypted
          example: 44ssw0rd*
    ResponseEncriptData:
      type: object
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Indicates whether the service was executed
          example: true
        encryptedData:
          $ref: '#/components/schemas/ResponseEncriptData_encryptedData'
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge
          example: success
    ResponseEncriptData_encryptedData:
      type: object
      properties:
        password:
          maxLength: 200
          type: string
          description: Phrase or password encrypted
          example: gs7VonfE7UZukby0Yglx…
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
