---
openapi: 3.0.0
info:
  title: Validate Device Activation
  description: Service to validate whether the client's device is already active or registered in the system.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/jesusemprendesys/validateDeviceActivation/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: validateDeviceActivation
  description: Service to validate whether the client's device is already active or registered in the system.
paths:
  /apiOperations/enrollment/validateDeviceActivation:
    post:
      tags:
      - validateDeviceActivation
      summary: Validate Device Activation
      operationId: validateDeviceActivation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestValidateDeviceActivation'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response validateDeviceActivation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseValidateDeviceActivation'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestValidateDeviceActivation:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        phoneNumber:
          maxLength: 12
          type: string
          description: phone number
          example: "5568576731"
    ResponseValidateDeviceActivation:
      type: object
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Indicates whether the service was executed.
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
