---
openapi: 3.0.1
info:
  title: Get Calculate Comission
  description: Service to Get Calculate Comission.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/getCalculateCommission/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: getCalculateCommission
  description: Service to Get Calculate Comission.
paths:
  /apiOperations/common/getCalculateCommission:
    post:
      tags:
      - getCalculateCommission
      summary: Get Calculate Comission
      operationId: getCalculateCommission
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetCalCommission'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response getCalculateCommission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetCalCommission'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestGetCalCommission:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        amount:
          type: integer
          description: Amount of comission
          example: 10
        account:
          maxLength: 20
          type: string
          description: Account of comission
          example: "402653207"
    ResponseGetCalCommission:
      type: object
      properties:
        success:
          maxLength: 10
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        amountCommission:
          maxLength: 40
          type: number
          description: Amount comission
          example: 20
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
