---
openapi: 3.0.0
info:
  title: Update Account Beneficiary
  description: This service is for update beneficiary
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/updateAccountBeneficiary/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Update Account Beneficiary
  description: Update Account Beneficiary
paths:
  /apiOperations/onboarding/updateAccountBebeficiary:
    post:
      tags:
      - Update Account Beneficiary
      summary: Update Account Beneficiary
      operationId: updateAccountBebeficiary
      requestBody:
        description: Request Account Beneficiary
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBeneficiaryRequest'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response Create Customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterBeneficiaryResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    RegisterBeneficiaryRequest:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        account:
          maxLength: 20
          minLength: 10
          type: string
          description: account number
        beneficiaryId:
          maxLength: 1
          minLength: 12
          type: integer
          description: code beneficiary id
        firtname:
          maximum: 20
          minimum: 1
          type: string
          description: firts name customer
          example: Jose
        secondName:
          maximum: 20
          minimum: 1
          type: string
          description: second name customer
          example: Carlos
        lastName:
          maximum: 20
          minimum: 1
          type: string
          description: last name customer
          example: Olmos
        secondLastName:
          maximum: 20
          minimum: 1
          type: string
          description: second last name customer
          example: Solis
        zipcode:
          maxLength: 5
          minLength: 5
          type: string
          description: Zip code
          example: "10000"
        province:
          maxLength: 2
          minLength: 1
          type: string
          description: Province ID, (Use the "getCatalog" service with table cl_pais)
          example: "9"
        city:
          maxLength: 10
          minLength: 1
          type: string
          description: City of residence ID,for example 9011 (Use the "getCatalog" service with table cl_ciudad)
          example: "9011"
        referenceAddress:
          maxLength: 40
          type: string
          description: last name customer
          example: street park
        codeColony:
          maxLength: 20
          type: string
          description: ColonyId (Use the "getCatalog" service with the cl_parroquia table to get the name)
          example: "90100001"
        relationship:
          maxLength: 20
          type: string
          description: relationship with owner account
          example: CASADO
        percentage:
          maximum: 100
          minimum: 1
          maxLength: 6
          minLength: 1
          type: number
          description: percentage amount beneficiary
          example: 100
    RegisterBeneficiaryResponse:
      properties:
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
