---
openapi: 3.0.0
info:
  title: Update Customer Address
  description: Service update address customer
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APICobisCorp2023/updateCustomerAddress/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/APITesting2023/updateCustomerAddress/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Update Customer's
  description: This Service is used for Update Customer Address
paths:
  /apiOperations/customer/updateCustomerAddress:
    post:
      tags:
      - Update Customer's
      summary: Update customer address
      operationId: updateCustomerAddress
      requestBody:
        description: Request to update customer address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerAddressRequest'
        required: true
      responses:
        "400":
          description: Description of errors regarding the execution of the service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response update customer address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerAddressResponse'
      security:
      - bearerAuth: []
components:
  schemas:
    UpdateCustomerAddressRequest:
      required:
      - addressTypeCode
      - anotherAddress
      - city
      - country
      - externalCustomerId
      - externalNumber
      - internalNumberl
      - propertyTypeCode
      - province
      - referenceAddress
      - street
      - subdivisioncode
      - timeCurrentRecide
      - townCode
      - zipcode
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        zipcode:
          maximum: 5
          minimum: 5
          type: string
          description: Zip code
          example: "10000"
        province:
          maximum: 2
          minimum: 1
          type: string
          description: Province ID, (Use the "getCatalog" service with table cl_pais)
          example: "9"
        city:
          maximum: 10
          minimum: 1
          type: string
          description: City of residence ID,for example 9011 (Use the "getCatalog" service with table cl_ciudad)
          example: "9011"
        subdivisioncode:
          maximum: 10
          minimum: 1
          type: string
          description: Id of colony or parish of residence,  (Use the "getCatalog" service with table cl_parroquia)
          example: "90111959"
        townCode:
          maximum: 6
          minimum: 1
          type: string
          description: Id of locality of residence (Use the service searchLocationCatalogwith City of residence ID)
          example: "146"
        street:
          maximum: 25
          minimum: 1
          type: string
          description: street name of the customer's home
          example: my street
        externalNumber:
          maximum: 10
          minimum: 1
          type: string
          description: External number of the customer's home
          example: "10"
        internalNumber:
          maximum: 5
          minimum: 1
          type: string
          description: Inside number of the customer's home  (NA is always 0 )
          example: "0"
        referenceAddress:
          maximum: 20
          minimum: 1
          type: string
          description: Reference Address
          example: street park
        timeCurrentRecide:
          maximum: 3
          minimum: 1
          type: string
          description: Customer time current residence
          example: "3"
        addressTypeCode:
          maximum: 5
          minimum: 1
          type: string
          description: Customer type address (Use the "getCatalog" service with table cl_tdireccion)
          example: AE
        propertyTypeCode:
          maximum: 5
          minimum: 1
          type: string
          description: Type of provider where you live (Use the "getCatalog" service with table cl_tpropiedad)
          example: PRO
    UpdateCustomerAddressResponse:
      properties:
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
    Error400052:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400052_Message'
      description: The selected address type does not exist in the catalog
    Error400053:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400053_Message'
      description: The selected property type does not exist in the catalog
    Error400057:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400057_Message'
      description: Error the zip code you entered does not exist
    Error400058:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400058_Message'
      description: Error the municipality or city does not exist
    Error400059:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400059_Message'
      description: Error the colony or parish does not exist
    Error400060:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400060_Message'
      description: Error the location does not exist
    Error400099:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400099_Message'
      description: The entered customer code does not exist
    Error400129:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400129_Message'
      description: The zipcode is required
    Error400130:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400130_Message'
      description: The province or state is required
    Error400131:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400131_Message'
      description: The city or municipality is required
    Error400132:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400132_Message'
      description: The colony is required
    Error400133:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400133_Message'
      description: The location is required
    Error400134:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400134_Message'
      description: The address type is required
    Error400135:
      type: object
      properties:
        success:
          type: boolean
          example: false
        Message:
          $ref: '#/components/schemas/Error400135_Message'
      description: Property type is required
    inline_response_400:
      oneOf:
      - $ref: '#/components/schemas/Error400052'
      - $ref: '#/components/schemas/Error400053'
      - $ref: '#/components/schemas/Error400057'
      - $ref: '#/components/schemas/Error400058'
      - $ref: '#/components/schemas/Error400059'
      - $ref: '#/components/schemas/Error400060'
      - $ref: '#/components/schemas/Error400099'
      - $ref: '#/components/schemas/Error400129'
      - $ref: '#/components/schemas/Error400130'
      - $ref: '#/components/schemas/Error400131'
      - $ref: '#/components/schemas/Error400132'
      - $ref: '#/components/schemas/Error400133'
      - $ref: '#/components/schemas/Error400134'
      - $ref: '#/components/schemas/Error400135'
    Error400052_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400052
        message:
          type: string
          description: message error
          example: The selected address type does not exist in the catalog
    Error400053_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400053
        message:
          type: string
          description: message error
          example: The selected property type does not exist in the catalog
    Error400057_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400057
        message:
          type: string
          description: message error
          example: Error the zip code you entered does not exist
    Error400058_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400058
        message:
          type: string
          description: message error
          example: Error the municipality or city does not exist
    Error400059_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400059
        message:
          type: string
          description: message error
          example: Error the colony or parish does not exist
    Error400060_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400060
        message:
          type: string
          description: message error
          example: Error the location does not exist
    Error400099_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400099
        message:
          type: string
          description: message error
          example: The entered customer code does not exist
    Error400129_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400129
        message:
          type: string
          description: message error
          example: The zipcode is required
    Error400130_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400130
        message:
          type: string
          description: message error
          example: The province or state is required
    Error400131_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400131
        message:
          type: string
          description: message error
          example: The city or municipality is required
    Error400132_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400132
        message:
          type: string
          description: message error
          example: The colony is required
    Error400133_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400133
        message:
          type: string
          description: message error
          example: The location is required
    Error400134_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400134
        message:
          type: string
          description: message error
          example: The address type is required
    Error400135_Message:
      type: object
      properties:
        code:
          type: integer
          description: code error
          example: 400135
        message:
          type: string
          description: message error
          example: Property type is required
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
