---
openapi: 3.0.0
info:
  title: Register Account
  description: Service to register beneficiaries for transfers..
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/RegisterAccounts/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Register Account
  description: Service to register beneficiaries for transfers.
paths:
  /apiOperations/accounts/registerAccount:
    post:
      tags:
      - Register Account
      summary: Service to register beneficiaries for transfers.
      operationId: registerAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestRegisterAccount'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Register Account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseRegisterAccount'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestRegisterAccount:
      properties:
        phoneNumber:
          maxLength: 10
          minLength: 1
          type: string
          description: Customer phone number
          example: "525568576731"
        productOwner:
          maxLength: 30
          type: string
          description: Product name
          example: same bank
        productAlias:
          maxLength: 30
          type: string
          description: Product aliases
          example: GUSTAVO MARTINEZ BURGUETES
        productId:
          maxLength: 5
          minLength: 1
          type: integer
          description: Product Id
          example: 4
        productNumber:
          maxLength: 2
          type: string
          description: Number of product
          example: "03000030036"
        currencyId:
          maxLength: 2
          type: integer
          description: Id of currency
          example: 0
        channelId:
          maxLength: 2
          type: integer
          description: Id of channel
          example: 8
        localBankId:
          maxLength: 10
          type: integer
          description: Id of local bank
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
    ResponseRegisterAccount:
      properties:
        success:
          type: boolean
          description: result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
        statusRegister:
          maxLength: 20
          type: string
          description: Concept movement
          example: existing
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
