---
openapi: 3.0.0
info:
  title: Get catalog
  description: This service is used for get catalog's
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/GetCatalog/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Get Catalog's
  description: This Service is used for get data catalogs
paths:
  /apiOperations/common/getCatalog:
    post:
      tags:
      - Get Catalog
      summary: Get Catalog
      operationId: getCatalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCatalog'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Get data catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCatalog'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestCatalog:
      properties:
        catalogueTable:
          maxLength: 20
          minLength: 1
          type: string
          description: Catalog  Name
          example: cl_referencia_tiempo
    ResponseCatalog:
      type: object
      properties:
        catalogueItems:
          type: array
          description: Catalogo de items
          items:
            $ref: '#/components/schemas/CatalogueItems'
        success:
          type: boolean
          description: message result process
          example: true
        message:
          $ref: '#/components/schemas/Message'
    CatalogueItems:
      type: object
      properties:
        code:
          type: string
          description: id catalog
          example: "5"
        name:
          type: string
          description: catalog value
          example: 5 รณ mas
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
