---
openapi: 3.0.0
info:
  title: Get Colony by Municipality
  description: Service to obtain the identifier and name of the colony corresponding to a postal code and municipality.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/GetColonyByMunicipality/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Get Colony by Municipality
  description: Service to obtain the identifier and name of the colony corresponding to a postal code and municipality.
paths:
  /apiOperations/onbording/getColonyByMunicipality:
    post:
      tags:
      - Get Colony by Municipality
      summary: Get Colony by Municipality
      operationId: getColonyByMunicipality
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetColonyByMunicipality'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Get Colony by Municipality
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetColonyByMunicipality'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestGetColonyByMunicipality:
      properties:
        zipCode:
          maxLength: 5
          minLength: 1
          type: string
          description: Zip code
          example: "01000"
        municipality:
          maxLength: 10
          minLength: 1
          type: string
          description: City or Municipality ID
          example: "9010"
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
    ResponseGetColonyByMunicipality:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates whether the service was executed
          example: true
        addressTypeItems:
          type: array
          items:
            $ref: '#/components/schemas/AddressTypeItems'
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
    AddressTypeItems:
      type: object
      properties:
        code:
          maxLength: 20
          minLength: 1
          type: string
          description: Colony or Parish ID
          example: "90100001"
        value:
          maxLength: 20
          minLength: 1
          type: string
          description: Colony or Parish name
          example: SAN ANGEL
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  parameters:
    token:
      name: token
      in: header
      description: Authentication token
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
