---
openapi: 3.0.0
info:
  title: Disable Debit Card
  description: Service to Disable Debit Card
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/DisableDebitCard/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Disable Debit Card
  description: Service to Disable Debit Card
paths:
  /apiOperations/accounts/disableDebitCard:
    post:
      tags:
      - Disable Debit Card
      summary: Service to Disable Debit Card
      operationId: disableDebitCard
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestDisableDebitCard'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Disable Debit Card
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDisableDebitCard'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestDisableDebitCard:
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        numberDeitCard:
          maxLength: 25
          minLength: 1
          type: string
          description: Number debit card
          example: 7544-5846-2581-6845
    ResponseDisableDebitCard:
      properties:
        success:
          maxLength: 1
          type: boolean
          description: Result process
          example: true
        state:
          maxLength: 1
          type: string
          description: Current card status
          example: A
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
