---
openapi: 3.0.0
info:
  title: Create Saving Account
  description: Service to create a savings account for an existing customer.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/CreateSavingAccount/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Create Saving Account
  description: Service to create a savings account for an existing customer.
paths:
  /apiOperations/customer/createSavingAccount:
    post:
      tags:
      - Create Saving Account
      summary: Service to create a savings account for an existing customer
      operationId: createSavingAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCreateSavingAccount'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Saving Account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCreateSavingAccount'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestCreateSavingAccount:
      properties:
        isMati:
          maxLength: 1
          minLength: 1
          type: string
          description: Indicates whether the customer's identity was verified using the services of the provider META/MATI(S or N)
          example: S
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
    ResponseCreateSavingAccount:
      properties:
        success:
          type: boolean
          description: result process
          example: true
        productNumber:
          maxLength: 20
          minLength: 1
          type: string
          description: Savings account number created
          example: "03000021176"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
