---
openapi: 3.0.1
info:
  title: Check Account Details
  description: Service to obtain the detail and balance of an existing savings account.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/APITesting2023/getBalancesDetail/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: getBalancesDetail
  description: Service to obtain the detail and balance of an existing savings account.
paths:
  /apiOperations/accounts/getBalancesDetail:
    post:
      tags:
      - getBalancesDetail
      summary: Check Account Details
      operationId: getBalancesDetail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGetBalancesDetail'
        required: true
      responses:
        "400":
          description: The data sent is incorrect or corrupted
        "500":
          description: An error occurred on the server
        "401":
          description: Unauthorized service
        "403":
          description: The request has been denied.
        "200":
          description: Response getBalancesDetail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetBalancesDetail'
      security:
      - bearerAuth: []
components:
  schemas:
    RequestGetBalancesDetail:
      type: object
      properties:
        externalCustomerId:
          maxLength: 12
          type: integer
          description: External Customer Id
          example: 220
        productNumber:
          maxLength: 20
          type: string
          description: Savings account number
          example: "402653207"
    ResponseGetBalancesDetail:
      type: object
      properties:
        success:
          maxLength: 10
          type: string
          description: Indicates whether the service was executed.
          example: "true"
        accountName:
          maxLength: 40
          type: string
          description: Account Name
          example: JOSE OLMOS SOLIS
        accountStatus:
          maxLength: 10
          type: string
          description: Account status
          example: ACTIVA
        availableBalance:
          maxLength: 8
          type: number
          description: Available balance
          example: 11.52
        averageBalance:
          maxLength: 8
          type: number
          description: Average balance
          example: 0
        currencyId:
          maxLength: 4
          type: integer
          description: Currency ID
          example: 0
        deliveryAddress:
          maxLength: 30
          type: string
          description: Delivery
          example: RETENCION EN CORPORATIVO
        freezingsNumber:
          maxLength: 4
          type: string
          description: Block id
          example: "0"
        frozenAmount:
          maxLength: 8
          type: number
          description: Amount block
          example: 1
        lastCutoffBalance:
          maxLength: 0
          type: number
          description: Amount last cut
          example: 0
        lastOperationDate:
          maxLength: 10
          type: string
          description: Last operation date
          example: 30/09/2022
        openingDate:
          maxLength: 10
          type: string
          description: Open account date
          example: 22/02/2021
        overdraftAmount:
          maxLength: 8
          type: number
          description: Overdraft amount
          example: 0
        productBalance:
          maxLength: 8
          type: number
          description: Product Balance
          example: 0
        productId:
          maxLength: 4
          type: integer
          description: PRoduct Id
          example: 0
        reserveBalance:
          maxLength: 8
          type: number
          description: Amount Reserved
          example: 0
        restrainedAmount:
          maxLength: 8
          type: number
          description: Blocked Amount
          example: 0
        toDrawBalance:
          maxLength: 8
          type: number
          description: Draw Balance
          example: 10.52
        accountingBalance:
          maxLength: 8
          type: number
          description: Balance
          example: 11.52
        ofical:
          maxLength: 10
          type: string
          description: Official Acount
          example: sa
        clabeAccountNumber:
          maxLength: 18
          type: string
          description: 8-digit interbank clabe
          example: "646180283000000020"
        idDebitCard:
          maxLength: 4
          type: integer
          description: Debit card ID
          example: 0
        debitCardNumber:
          maxLength: 20
          type: string
          description: Debit Card Number
          example: N/A
        stateDebitCard:
          maxLength: 1
          type: string
          description: Debit Card Status
          example: "N"
        message:
          $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          maxLength: 10
          type: integer
          description: Result Code
          example: 0
        message:
          maxLength: 500
          type: string
          description: Result Mesagge Code
          example: success
  responses:
    Unauthorized:
      description: Unauthorized service
    NotFound:
      description: The information does not exist
    BadRequest:
      description: The data sent is incorrect or corrupted
    ServerError:
      description: An error occurred on the server
    "403Forbidden":
      description: The request has been denied.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
