
package ws.cobiscorp.ecobis.bankingservicesoperatinons.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cobiscorp.ecobis.bankingservicesoperation.dto.PayOrderDetailRequest;
import com.cobiscorp.cobis.cts.sdf.dto2.CTSServiceResponseTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterbankWireReceptionService", targetNamespace = "http://service.bankingservicesoperatinons.ecobis.cobiscorp.ws/")
@XmlSeeAlso({
    cobiscorp.ecobis.bankingservicesoperatinons.service.ObjectFactory.class,
    cobiscorp.ecobis.bankingservicesoperation.dto.ObjectFactory.class,
    cobiscorp.ecobis.commons.dto2.ObjectFactory.class,
    com.cobiscorp.cobis.cts.sdf.dto2.ObjectFactory.class
})
public interface InterbankWireReceptionService {


    /**
     * 
     * @param inPayOrderDetailRequest
     * @return
     *     returns com.cobiscorp.cobis.cts.sdf.dto2.CTSServiceResponseTO
     */
    @WebMethod(operationName = "FrameReceptionService", action = "http://service.bankingservicesoperatinons.ecobis.cobiscorp.ws/InterbankWireReceptionService/FrameReceptionService")
    @WebResult(name = "outFrameReceptionServiceResponse", targetNamespace = "http://service.bankingservicesoperatinons.ecobis.cobiscorp")
    @RequestWrapper(localName = "FrameReceptionService", targetNamespace = "http://service.bankingservicesoperatinons.ecobis.cobiscorp", className = "cobiscorp.ecobis.bankingservicesoperatinons.service.FrameReceptionService")
    @ResponseWrapper(localName = "FrameReceptionServiceResponse", targetNamespace = "http://service.bankingservicesoperatinons.ecobis.cobiscorp", className = "cobiscorp.ecobis.bankingservicesoperatinons.service.FrameReceptionServiceResponse")
    public CTSServiceResponseTO frameReceptionService(
        @WebParam(name = "inPayOrderDetailRequest", targetNamespace = "http://service.bankingservicesoperatinons.ecobis.cobiscorp")
        PayOrderDetailRequest inPayOrderDetailRequest);

}
