
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.clientesdto.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class DatosClientes implements Serializable {
  private int ente;
  private String nombre;
  private String cedula;
  private java.util.Calendar fechaCrea;
  public int getEnte(){
    return this.ente;
  }
  public void setEnte(int ente ){
    this.ente=ente;
  }
  public String getNombre(){
    return this.nombre;
  }
  public void setNombre(String nombre ){
    this.nombre=nombre;
  }
  public String getCedula(){
    return this.cedula;
  }
  public void setCedula(String cedula ){
    this.cedula=cedula;
  }
  public java.util.Calendar getFechaCrea(){
    return this.fechaCrea;
  }
  public void setFechaCrea(java.util.Calendar fechaCrea ){
    this.fechaCrea=fechaCrea;
  }
}
