
package ws.cobiscorp.ecobis.bankingservicesoperations.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InterbankFrameReceptionService", targetNamespace = "http://service.bankingservicesoperations.ecobis.cobiscorp.ws/", wsdlLocation = "file:/C:/Trafalgar/middleware_22/trf-ib-middleware/Project_SG_IB/Wsdl_InternetBanking/Code/WS/webapp/wsdl/COBISCorp.eCOBIS.BankingServicesOperations.Service.wsdl")
public class InterbankFrameReceptionService_Service
    extends Service
{

    private final static URL INTERBANKFRAMERECEPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTERBANKFRAMERECEPTIONSERVICE_EXCEPTION;
    private final static QName INTERBANKFRAMERECEPTIONSERVICE_QNAME = new QName("http://service.bankingservicesoperations.ecobis.cobiscorp.ws/", "InterbankFrameReceptionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Trafalgar/middleware_22/trf-ib-middleware/Project_SG_IB/Wsdl_InternetBanking/Code/WS/webapp/wsdl/COBISCorp.eCOBIS.BankingServicesOperations.Service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTERBANKFRAMERECEPTIONSERVICE_WSDL_LOCATION = url;
        INTERBANKFRAMERECEPTIONSERVICE_EXCEPTION = e;
    }

    public InterbankFrameReceptionService_Service() {
        super(__getWsdlLocation(), INTERBANKFRAMERECEPTIONSERVICE_QNAME);
    }

    public InterbankFrameReceptionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTERBANKFRAMERECEPTIONSERVICE_QNAME, features);
    }

    public InterbankFrameReceptionService_Service(URL wsdlLocation) {
        super(wsdlLocation, INTERBANKFRAMERECEPTIONSERVICE_QNAME);
    }

    public InterbankFrameReceptionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTERBANKFRAMERECEPTIONSERVICE_QNAME, features);
    }

    public InterbankFrameReceptionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterbankFrameReceptionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InterbankFrameReceptionService
     */
    @WebEndpoint(name = "InterbankFrameReceptionServiceSOAP")
    public InterbankFrameReceptionService getInterbankFrameReceptionServiceSOAP() {
        return super.getPort(new QName("http://service.bankingservicesoperations.ecobis.cobiscorp.ws/", "InterbankFrameReceptionServiceSOAP"), InterbankFrameReceptionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterbankFrameReceptionService
     */
    @WebEndpoint(name = "InterbankFrameReceptionServiceSOAP")
    public InterbankFrameReceptionService getInterbankFrameReceptionServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bankingservicesoperations.ecobis.cobiscorp.ws/", "InterbankFrameReceptionServiceSOAP"), InterbankFrameReceptionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTERBANKFRAMERECEPTIONSERVICE_EXCEPTION!= null) {
            throw INTERBANKFRAMERECEPTIONSERVICE_EXCEPTION;
        }
        return INTERBANKFRAMERECEPTIONSERVICE_WSDL_LOCATION;
    }

}
