//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolaNetReader.CalixtaServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.calixtaondemand.com", ConfigurationName="CalixtaServices.GatewayPortType")]
    public interface GatewayPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensajes(ConsolaNetReader.CalixtaServices.Transaccion mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajesAsync(ConsolaNetReader.CalixtaServices.Transaccion mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvioEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EstadoEnvioEmail(int cte, string email, string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvioEmail", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EstadoEnvioEmailAsync(int cte, string email, string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EventosEnvioEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        ConsolaNetReader.CalixtaServices.EventosEnvioEmailResponse EventosEnvioEmail(ConsolaNetReader.CalixtaServices.EventosEnvioEmailRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EventosEnvioEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EventosEnvioEmailResponse> EventosEnvioEmailAsync(ConsolaNetReader.CalixtaServices.EventosEnvioEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string EnviaEmail(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaEmail", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> EnviaEmailAsync(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajesCSV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensajesCSV(ConsolaNetReader.CalixtaServices.TransaccionCSV mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajesCSV", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajesCSVAsync(ConsolaNetReader.CalixtaServices.TransaccionCSV mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensaje(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensaje", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajeAsync(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsolaNetReader.CalixtaServices.RespEnvio EstadoEnvio(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvio", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.RespEnvio> EstadoEnvioAsync(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsolaNetReader.CalixtaServices.EdoMensajes[] EstadoMensajes(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EdoMensajes[]> EstadoMensajesAsync(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensajeOL(
                    int idCliente, 
                    string email, 
                    string password, 
                    string tipo, 
                    string telefono, 
                    string mensaje, 
                    int idivr, 
                    string fechaInicio, 
                    string campoAux, 
                    string asunto, 
                    string url, 
                    string idApp, 
                    string token, 
                    ConsolaNetReader.CalixtaServices.Parametro[] parametros, 
                    string idOrigen, 
                    int mismoOrigen, 
                    int minutosReintento, 
                    int cantidadIntentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOL", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajeOLAsync(
                    int idCliente, 
                    string email, 
                    string password, 
                    string tipo, 
                    string telefono, 
                    string mensaje, 
                    int idivr, 
                    string fechaInicio, 
                    string campoAux, 
                    string asunto, 
                    string url, 
                    string idApp, 
                    string token, 
                    ConsolaNetReader.CalixtaServices.Parametro[] parametros, 
                    string idOrigen, 
                    int mismoOrigen, 
                    int minutosReintento, 
                    int cantidadIntentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOLRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefResponse EnviaMensajeOLRef(ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOLRef", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefResponse> EnviaMensajeOLRefAsync(ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EstadoMensajeOLRef(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRef", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EstadoMensajeOLRefAsync(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRefAux", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxResponse EstadoMensajeOLAux(ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRefAux", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxResponse> EstadoMensajeOLAuxAsync(ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#AgregaALista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int AgregaALista(int idCliente, string email, string password, int idLista, string telefono, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#AgregaALista", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> AgregaAListaAsync(int idCliente, string email, string password, int idLista, string telefono, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ExisteEnLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int ExisteEnLista(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ExisteEnLista", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> ExisteEnListaAsync(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EliminaDeLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EliminaDeLista(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EliminaDeLista", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EliminaDeListaAsync(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#GeneraLigaCorta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        ConsolaNetReader.CalixtaServices.GeneraLigaCortaResponse GeneraLigaCorta(ConsolaNetReader.CalixtaServices.GeneraLigaCortaRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#GeneraLigaCorta", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.GeneraLigaCortaResponse> GeneraLigaCortaAsync(ConsolaNetReader.CalixtaServices.GeneraLigaCortaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#CreaEnvioEmailS3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Response CreaEnvioEmailS3(ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#CreaEnvioEmailS3", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Response> CreaEnvioEmailS3Async(ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#AgregaArchivoAEmailS3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        int AgregaArchivoAEmailS3(int idCliente, string email, string password, int idEnvio, string tipo, string base64FileContent, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#AgregaArchivoAEmailS3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<int> AgregaArchivoAEmailS3Async(int idCliente, string email, string password, int idEnvio, string tipo, string base64FileContent, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConfirmaEnvioEmailS3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        int ConfirmaEnvioEmailS3(
                    int idCliente, 
                    string email, 
                    string password, 
                    int idEnvio, 
                    string nombreEnvio, 
                    string csvBase64, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string asunto, 
                    string incrustaImagenes, 
                    string cuerpoTextoBase64, 
                    string cuerpoHTMLBase64, 
                    string nombreAdjuntosIndividuales, 
                    int enviarSiFaltanAdjuntos, 
                    string fechaInicio, 
                    string fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConfirmaEnvioEmailS3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<int> ConfirmaEnvioEmailS3Async(
                    int idCliente, 
                    string email, 
                    string password, 
                    int idEnvio, 
                    string nombreEnvio, 
                    string csvBase64, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string asunto, 
                    string incrustaImagenes, 
                    string cuerpoTextoBase64, 
                    string cuerpoHTMLBase64, 
                    string nombreAdjuntosIndividuales, 
                    int enviarSiFaltanAdjuntos, 
                    string fechaInicio, 
                    string fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConsultaCarrier", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        ConsolaNetReader.CalixtaServices.ConsultaCarrierResponse ConsultaCarrier(ConsolaNetReader.CalixtaServices.ConsultaCarrierRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConsultaCarrier", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.ConsultaCarrierResponse> ConsultaCarrierAsync(ConsolaNetReader.CalixtaServices.ConsultaCarrierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConsultaSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsolaNetReader.CalixtaServices.Saldos[] ConsultaSaldo(int idCliente, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConsultaSaldo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.Saldos[]> ConsultaSaldoAsync(int idCliente, string email, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Transaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private string tipoField;
        
        private string fechaHoraField;
        
        private Mensaje[] mensajesField;
        
        private int idivrField;
        
        /// <remarks/>
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        public Mensaje[] mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
                this.RaisePropertyChanged("mensajes");
            }
        }
        
        /// <remarks/>
        public int idivr {
            get {
                return this.idivrField;
            }
            set {
                this.idivrField = value;
                this.RaisePropertyChanged("idivr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Mensaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telefonoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Saldos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string servicioField;
        
        private double disponibleField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        /// <remarks/>
        public double disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
                this.RaisePropertyChanged("disponible");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Parametro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class EdoMensajes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private string telefonoField;
        
        private double costoField;
        
        private string fechaHoraField;
        
        private string estadoField;
        
        private string listaField;
        
        private int idEnvioField;
        
        private int idEstadoField;
        
        private string mensajeField;
        
        private string destinoField;
        
        private string campoAuxField;
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        public string lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("lista");
            }
        }
        
        /// <remarks/>
        public int idEnvio {
            get {
                return this.idEnvioField;
            }
            set {
                this.idEnvioField = value;
                this.RaisePropertyChanged("idEnvio");
            }
        }
        
        /// <remarks/>
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("destino");
            }
        }
        
        /// <remarks/>
        public string campoAux {
            get {
                return this.campoAuxField;
            }
            set {
                this.campoAuxField = value;
                this.RaisePropertyChanged("campoAux");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class RespEnvio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private double fInicioField;
        
        private string camposField;
        
        private string descripcionField;
        
        private string listaField;
        
        private double porField;
        
        private int tipoField;
        
        private int idUsuarioField;
        
        private int especieField;
        
        private int estadoField;
        
        private double costoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public double fInicio {
            get {
                return this.fInicioField;
            }
            set {
                this.fInicioField = value;
                this.RaisePropertyChanged("fInicio");
            }
        }
        
        /// <remarks/>
        public string campos {
            get {
                return this.camposField;
            }
            set {
                this.camposField = value;
                this.RaisePropertyChanged("campos");
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        public string lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("lista");
            }
        }
        
        /// <remarks/>
        public double por {
            get {
                return this.porField;
            }
            set {
                this.porField = value;
                this.RaisePropertyChanged("por");
            }
        }
        
        /// <remarks/>
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        public int especie {
            get {
                return this.especieField;
            }
            set {
                this.especieField = value;
                this.RaisePropertyChanged("especie");
            }
        }
        
        /// <remarks/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class TransaccionEnvios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private int idEnvioField;
        
        /// <remarks/>
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public int idEnvio {
            get {
                return this.idEnvioField;
            }
            set {
                this.idEnvioField = value;
                this.RaisePropertyChanged("idEnvio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class TransaccionCSV : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private string tipoField;
        
        private string fechaHoraField;
        
        private string csvField;
        
        private string mensajeField;
        
        private int idivrField;
        
        private string nombreEnvioField;
        
        /// <remarks/>
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        public string csv {
            get {
                return this.csvField;
            }
            set {
                this.csvField = value;
                this.RaisePropertyChanged("csv");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public int idivr {
            get {
                return this.idivrField;
            }
            set {
                this.idivrField = value;
                this.RaisePropertyChanged("idivr");
            }
        }
        
        /// <remarks/>
        public string nombreEnvio {
            get {
                return this.nombreEnvioField;
            }
            set {
                this.nombreEnvioField = value;
                this.RaisePropertyChanged("nombreEnvio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Eventos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private string tipoField;
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventosEnvioEmail", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EventosEnvioEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string id;
        
        public EventosEnvioEmailRequest() {
        }
        
        public EventosEnvioEmailRequest(int cte, string email, string password, string id) {
            this.cte = cte;
            this.email = email;
            this.password = password;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventosEnvioEmailResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EventosEnvioEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConsolaNetReader.CalixtaServices.Eventos[] eventos;
        
        public EventosEnvioEmailResponse() {
        }
        
        public EventosEnvioEmailResponse(int code, ConsolaNetReader.CalixtaServices.Eventos[] eventos) {
            this.code = code;
            this.eventos = eventos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviaMensajeOLRef", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EnviaMensajeOLRefRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int idivr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string campoAux;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string asunto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string idApp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public ConsolaNetReader.CalixtaServices.Parametro[] parametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string idOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public int mismoOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public int minutosReintento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public int cantidadIntentos;
        
        public EnviaMensajeOLRefRequest() {
        }
        
        public EnviaMensajeOLRefRequest(
                    int idCliente, 
                    string email, 
                    string password, 
                    string tipo, 
                    string telefono, 
                    string mensaje, 
                    int idivr, 
                    string fechaInicio, 
                    string campoAux, 
                    string asunto, 
                    string url, 
                    string idApp, 
                    string token, 
                    ConsolaNetReader.CalixtaServices.Parametro[] parametros, 
                    string idOrigen, 
                    int mismoOrigen, 
                    int minutosReintento, 
                    int cantidadIntentos) {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.tipo = tipo;
            this.telefono = telefono;
            this.mensaje = mensaje;
            this.idivr = idivr;
            this.fechaInicio = fechaInicio;
            this.campoAux = campoAux;
            this.asunto = asunto;
            this.url = url;
            this.idApp = idApp;
            this.token = token;
            this.parametros = parametros;
            this.idOrigen = idOrigen;
            this.mismoOrigen = mismoOrigen;
            this.minutosReintento = minutosReintento;
            this.cantidadIntentos = cantidadIntentos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviaMensajeOLRefResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EnviaMensajeOLRefResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string referencia;
        
        public EnviaMensajeOLRefResponse() {
        }
        
        public EnviaMensajeOLRefResponse(int resultado, string referencia) {
            this.resultado = resultado;
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadoMensajeOLAux", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EstadoMensajeOLAuxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string campoAux;
        
        public EstadoMensajeOLAuxRequest() {
        }
        
        public EstadoMensajeOLAuxRequest(int idCliente, string email, string password, string campoAux) {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.campoAux = campoAux;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadoMensajeOLAuxResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EstadoMensajeOLAuxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string id;
        
        public EstadoMensajeOLAuxResponse() {
        }
        
        public EstadoMensajeOLAuxResponse(int resultado, string referencia, string id) {
            this.resultado = resultado;
            this.referencia = referencia;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraLigaCorta", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class GeneraLigaCortaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string url;
        
        public GeneraLigaCortaRequest() {
        }
        
        public GeneraLigaCortaRequest(int idCliente, string email, string password, string url) {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraLigaCortaResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class GeneraLigaCortaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ligaCorta;
        
        public GeneraLigaCortaResponse() {
        }
        
        public GeneraLigaCortaResponse(int resultado, string ligaCorta) {
            this.resultado = resultado;
            this.ligaCorta = ligaCorta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreaEnvioEmailS3", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class CreaEnvioEmailS3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public CreaEnvioEmailS3Request() {
        }
        
        public CreaEnvioEmailS3Request(int idCliente, string email, string password) {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreaEnvioEmailS3Response", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class CreaEnvioEmailS3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int idEnvio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sessionToken;
        
        public CreaEnvioEmailS3Response() {
        }
        
        public CreaEnvioEmailS3Response(int resultado, int idEnvio, string sessionToken) {
            this.resultado = resultado;
            this.idEnvio = idEnvio;
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCarrier", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class ConsultaCarrierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string telefono;
        
        public ConsultaCarrierRequest() {
        }
        
        public ConsultaCarrierRequest(int idCliente, string email, string password, string telefono) {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCarrierResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class ConsultaCarrierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int carrier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int resultado;
        
        public ConsultaCarrierResponse() {
        }
        
        public ConsultaCarrierResponse(int carrier, int resultado) {
            this.carrier = carrier;
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GatewayPortTypeChannel : ConsolaNetReader.CalixtaServices.GatewayPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayPortTypeClient : System.ServiceModel.ClientBase<ConsolaNetReader.CalixtaServices.GatewayPortType>, ConsolaNetReader.CalixtaServices.GatewayPortType {
        
        public GatewayPortTypeClient() {
        }
        
        public GatewayPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int EnviaMensajes(ConsolaNetReader.CalixtaServices.Transaccion mensajes) {
            return base.Channel.EnviaMensajes(mensajes);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajesAsync(ConsolaNetReader.CalixtaServices.Transaccion mensajes) {
            return base.Channel.EnviaMensajesAsync(mensajes);
        }
        
        public int EstadoEnvioEmail(int cte, string email, string password, int id) {
            return base.Channel.EstadoEnvioEmail(cte, email, password, id);
        }
        
        public System.Threading.Tasks.Task<int> EstadoEnvioEmailAsync(int cte, string email, string password, int id) {
            return base.Channel.EstadoEnvioEmailAsync(cte, email, password, id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsolaNetReader.CalixtaServices.EventosEnvioEmailResponse ConsolaNetReader.CalixtaServices.GatewayPortType.EventosEnvioEmail(ConsolaNetReader.CalixtaServices.EventosEnvioEmailRequest request) {
            return base.Channel.EventosEnvioEmail(request);
        }
        
        public int EventosEnvioEmail(int cte, string email, string password, string id, out ConsolaNetReader.CalixtaServices.Eventos[] eventos) {
            ConsolaNetReader.CalixtaServices.EventosEnvioEmailRequest inValue = new ConsolaNetReader.CalixtaServices.EventosEnvioEmailRequest();
            inValue.cte = cte;
            inValue.email = email;
            inValue.password = password;
            inValue.id = id;
            ConsolaNetReader.CalixtaServices.EventosEnvioEmailResponse retVal = ((ConsolaNetReader.CalixtaServices.GatewayPortType)(this)).EventosEnvioEmail(inValue);
            eventos = retVal.eventos;
            return retVal.code;
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EventosEnvioEmailResponse> EventosEnvioEmailAsync(ConsolaNetReader.CalixtaServices.EventosEnvioEmailRequest request) {
            return base.Channel.EventosEnvioEmailAsync(request);
        }
        
        public string EnviaEmail(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar) {
            return base.Channel.EnviaEmail(cte, email, password, nombreCamp, to, from, fromName, replyTo, subject, incrustarImagen, textEmail, htmlEmail, seleccionaAdjuntos, fileBase64, fileNameBase64, nombreArchivoPersonalizado, envioSinArchivo, fechaInicio, horaInicio, minutoInicio, listasNegras, referencia, campoAuxiliar);
        }
        
        public System.Threading.Tasks.Task<string> EnviaEmailAsync(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar) {
            return base.Channel.EnviaEmailAsync(cte, email, password, nombreCamp, to, from, fromName, replyTo, subject, incrustarImagen, textEmail, htmlEmail, seleccionaAdjuntos, fileBase64, fileNameBase64, nombreArchivoPersonalizado, envioSinArchivo, fechaInicio, horaInicio, minutoInicio, listasNegras, referencia, campoAuxiliar);
        }
        
        public int EnviaMensajesCSV(ConsolaNetReader.CalixtaServices.TransaccionCSV mensajes) {
            return base.Channel.EnviaMensajesCSV(mensajes);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajesCSVAsync(ConsolaNetReader.CalixtaServices.TransaccionCSV mensajes) {
            return base.Channel.EnviaMensajesCSVAsync(mensajes);
        }
        
        public int EnviaMensaje(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr) {
            return base.Channel.EnviaMensaje(idCliente, email, password, tipo, fechaHora, telefono, mensaje, idivr);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajeAsync(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr) {
            return base.Channel.EnviaMensajeAsync(idCliente, email, password, tipo, fechaHora, telefono, mensaje, idivr);
        }
        
        public ConsolaNetReader.CalixtaServices.RespEnvio EstadoEnvio(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoEnvio(idEnvio);
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.RespEnvio> EstadoEnvioAsync(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoEnvioAsync(idEnvio);
        }
        
        public ConsolaNetReader.CalixtaServices.EdoMensajes[] EstadoMensajes(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoMensajes(idEnvio);
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EdoMensajes[]> EstadoMensajesAsync(ConsolaNetReader.CalixtaServices.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoMensajesAsync(idEnvio);
        }
        
        public int EnviaMensajeOL(
                    int idCliente, 
                    string email, 
                    string password, 
                    string tipo, 
                    string telefono, 
                    string mensaje, 
                    int idivr, 
                    string fechaInicio, 
                    string campoAux, 
                    string asunto, 
                    string url, 
                    string idApp, 
                    string token, 
                    ConsolaNetReader.CalixtaServices.Parametro[] parametros, 
                    string idOrigen, 
                    int mismoOrigen, 
                    int minutosReintento, 
                    int cantidadIntentos) {
            return base.Channel.EnviaMensajeOL(idCliente, email, password, tipo, telefono, mensaje, idivr, fechaInicio, campoAux, asunto, url, idApp, token, parametros, idOrigen, mismoOrigen, minutosReintento, cantidadIntentos);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajeOLAsync(
                    int idCliente, 
                    string email, 
                    string password, 
                    string tipo, 
                    string telefono, 
                    string mensaje, 
                    int idivr, 
                    string fechaInicio, 
                    string campoAux, 
                    string asunto, 
                    string url, 
                    string idApp, 
                    string token, 
                    ConsolaNetReader.CalixtaServices.Parametro[] parametros, 
                    string idOrigen, 
                    int mismoOrigen, 
                    int minutosReintento, 
                    int cantidadIntentos) {
            return base.Channel.EnviaMensajeOLAsync(idCliente, email, password, tipo, telefono, mensaje, idivr, fechaInicio, campoAux, asunto, url, idApp, token, parametros, idOrigen, mismoOrigen, minutosReintento, cantidadIntentos);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefResponse ConsolaNetReader.CalixtaServices.GatewayPortType.EnviaMensajeOLRef(ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefRequest request) {
            return base.Channel.EnviaMensajeOLRef(request);
        }
        
        public int EnviaMensajeOLRef(
                    int idCliente, 
                    string email, 
                    string password, 
                    string tipo, 
                    string telefono, 
                    string mensaje, 
                    int idivr, 
                    string fechaInicio, 
                    string campoAux, 
                    string asunto, 
                    string url, 
                    string idApp, 
                    string token, 
                    ConsolaNetReader.CalixtaServices.Parametro[] parametros, 
                    string idOrigen, 
                    int mismoOrigen, 
                    int minutosReintento, 
                    int cantidadIntentos, 
                    out string referencia) {
            ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefRequest inValue = new ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefRequest();
            inValue.idCliente = idCliente;
            inValue.email = email;
            inValue.password = password;
            inValue.tipo = tipo;
            inValue.telefono = telefono;
            inValue.mensaje = mensaje;
            inValue.idivr = idivr;
            inValue.fechaInicio = fechaInicio;
            inValue.campoAux = campoAux;
            inValue.asunto = asunto;
            inValue.url = url;
            inValue.idApp = idApp;
            inValue.token = token;
            inValue.parametros = parametros;
            inValue.idOrigen = idOrigen;
            inValue.mismoOrigen = mismoOrigen;
            inValue.minutosReintento = minutosReintento;
            inValue.cantidadIntentos = cantidadIntentos;
            ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefResponse retVal = ((ConsolaNetReader.CalixtaServices.GatewayPortType)(this)).EnviaMensajeOLRef(inValue);
            referencia = retVal.referencia;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefResponse> EnviaMensajeOLRefAsync(ConsolaNetReader.CalixtaServices.EnviaMensajeOLRefRequest request) {
            return base.Channel.EnviaMensajeOLRefAsync(request);
        }
        
        public int EstadoMensajeOLRef(string referencia) {
            return base.Channel.EstadoMensajeOLRef(referencia);
        }
        
        public System.Threading.Tasks.Task<int> EstadoMensajeOLRefAsync(string referencia) {
            return base.Channel.EstadoMensajeOLRefAsync(referencia);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxResponse ConsolaNetReader.CalixtaServices.GatewayPortType.EstadoMensajeOLAux(ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxRequest request) {
            return base.Channel.EstadoMensajeOLAux(request);
        }
        
        public int EstadoMensajeOLAux(int idCliente, string email, string password, string campoAux, out string referencia, out string id) {
            ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxRequest inValue = new ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxRequest();
            inValue.idCliente = idCliente;
            inValue.email = email;
            inValue.password = password;
            inValue.campoAux = campoAux;
            ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxResponse retVal = ((ConsolaNetReader.CalixtaServices.GatewayPortType)(this)).EstadoMensajeOLAux(inValue);
            referencia = retVal.referencia;
            id = retVal.id;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxResponse> EstadoMensajeOLAuxAsync(ConsolaNetReader.CalixtaServices.EstadoMensajeOLAuxRequest request) {
            return base.Channel.EstadoMensajeOLAuxAsync(request);
        }
        
        public int AgregaALista(int idCliente, string email, string password, int idLista, string telefono, string nombre) {
            return base.Channel.AgregaALista(idCliente, email, password, idLista, telefono, nombre);
        }
        
        public System.Threading.Tasks.Task<int> AgregaAListaAsync(int idCliente, string email, string password, int idLista, string telefono, string nombre) {
            return base.Channel.AgregaAListaAsync(idCliente, email, password, idLista, telefono, nombre);
        }
        
        public int ExisteEnLista(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.ExisteEnLista(idCliente, email, password, idLista, telefono);
        }
        
        public System.Threading.Tasks.Task<int> ExisteEnListaAsync(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.ExisteEnListaAsync(idCliente, email, password, idLista, telefono);
        }
        
        public int EliminaDeLista(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.EliminaDeLista(idCliente, email, password, idLista, telefono);
        }
        
        public System.Threading.Tasks.Task<int> EliminaDeListaAsync(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.EliminaDeListaAsync(idCliente, email, password, idLista, telefono);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsolaNetReader.CalixtaServices.GeneraLigaCortaResponse ConsolaNetReader.CalixtaServices.GatewayPortType.GeneraLigaCorta(ConsolaNetReader.CalixtaServices.GeneraLigaCortaRequest request) {
            return base.Channel.GeneraLigaCorta(request);
        }
        
        public int GeneraLigaCorta(int idCliente, string email, string password, string url, out string ligaCorta) {
            ConsolaNetReader.CalixtaServices.GeneraLigaCortaRequest inValue = new ConsolaNetReader.CalixtaServices.GeneraLigaCortaRequest();
            inValue.idCliente = idCliente;
            inValue.email = email;
            inValue.password = password;
            inValue.url = url;
            ConsolaNetReader.CalixtaServices.GeneraLigaCortaResponse retVal = ((ConsolaNetReader.CalixtaServices.GatewayPortType)(this)).GeneraLigaCorta(inValue);
            ligaCorta = retVal.ligaCorta;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.GeneraLigaCortaResponse> GeneraLigaCortaAsync(ConsolaNetReader.CalixtaServices.GeneraLigaCortaRequest request) {
            return base.Channel.GeneraLigaCortaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Response ConsolaNetReader.CalixtaServices.GatewayPortType.CreaEnvioEmailS3(ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Request request) {
            return base.Channel.CreaEnvioEmailS3(request);
        }
        
        public int CreaEnvioEmailS3(int idCliente, string email, string password, out int idEnvio, out string sessionToken) {
            ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Request inValue = new ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Request();
            inValue.idCliente = idCliente;
            inValue.email = email;
            inValue.password = password;
            ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Response retVal = ((ConsolaNetReader.CalixtaServices.GatewayPortType)(this)).CreaEnvioEmailS3(inValue);
            idEnvio = retVal.idEnvio;
            sessionToken = retVal.sessionToken;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Response> CreaEnvioEmailS3Async(ConsolaNetReader.CalixtaServices.CreaEnvioEmailS3Request request) {
            return base.Channel.CreaEnvioEmailS3Async(request);
        }
        
        public int AgregaArchivoAEmailS3(int idCliente, string email, string password, int idEnvio, string tipo, string base64FileContent, string fileName) {
            return base.Channel.AgregaArchivoAEmailS3(idCliente, email, password, idEnvio, tipo, base64FileContent, fileName);
        }
        
        public System.Threading.Tasks.Task<int> AgregaArchivoAEmailS3Async(int idCliente, string email, string password, int idEnvio, string tipo, string base64FileContent, string fileName) {
            return base.Channel.AgregaArchivoAEmailS3Async(idCliente, email, password, idEnvio, tipo, base64FileContent, fileName);
        }
        
        public int ConfirmaEnvioEmailS3(
                    int idCliente, 
                    string email, 
                    string password, 
                    int idEnvio, 
                    string nombreEnvio, 
                    string csvBase64, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string asunto, 
                    string incrustaImagenes, 
                    string cuerpoTextoBase64, 
                    string cuerpoHTMLBase64, 
                    string nombreAdjuntosIndividuales, 
                    int enviarSiFaltanAdjuntos, 
                    string fechaInicio, 
                    string fechaFin) {
            return base.Channel.ConfirmaEnvioEmailS3(idCliente, email, password, idEnvio, nombreEnvio, csvBase64, from, fromName, replyTo, asunto, incrustaImagenes, cuerpoTextoBase64, cuerpoHTMLBase64, nombreAdjuntosIndividuales, enviarSiFaltanAdjuntos, fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<int> ConfirmaEnvioEmailS3Async(
                    int idCliente, 
                    string email, 
                    string password, 
                    int idEnvio, 
                    string nombreEnvio, 
                    string csvBase64, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string asunto, 
                    string incrustaImagenes, 
                    string cuerpoTextoBase64, 
                    string cuerpoHTMLBase64, 
                    string nombreAdjuntosIndividuales, 
                    int enviarSiFaltanAdjuntos, 
                    string fechaInicio, 
                    string fechaFin) {
            return base.Channel.ConfirmaEnvioEmailS3Async(idCliente, email, password, idEnvio, nombreEnvio, csvBase64, from, fromName, replyTo, asunto, incrustaImagenes, cuerpoTextoBase64, cuerpoHTMLBase64, nombreAdjuntosIndividuales, enviarSiFaltanAdjuntos, fechaInicio, fechaFin);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsolaNetReader.CalixtaServices.ConsultaCarrierResponse ConsolaNetReader.CalixtaServices.GatewayPortType.ConsultaCarrier(ConsolaNetReader.CalixtaServices.ConsultaCarrierRequest request) {
            return base.Channel.ConsultaCarrier(request);
        }
        
        public int ConsultaCarrier(int idCliente, string email, string password, string telefono, out int resultado) {
            ConsolaNetReader.CalixtaServices.ConsultaCarrierRequest inValue = new ConsolaNetReader.CalixtaServices.ConsultaCarrierRequest();
            inValue.idCliente = idCliente;
            inValue.email = email;
            inValue.password = password;
            inValue.telefono = telefono;
            ConsolaNetReader.CalixtaServices.ConsultaCarrierResponse retVal = ((ConsolaNetReader.CalixtaServices.GatewayPortType)(this)).ConsultaCarrier(inValue);
            resultado = retVal.resultado;
            return retVal.carrier;
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.ConsultaCarrierResponse> ConsultaCarrierAsync(ConsolaNetReader.CalixtaServices.ConsultaCarrierRequest request) {
            return base.Channel.ConsultaCarrierAsync(request);
        }
        
        public ConsolaNetReader.CalixtaServices.Saldos[] ConsultaSaldo(int idCliente, string email, string password) {
            return base.Channel.ConsultaSaldo(idCliente, email, password);
        }
        
        public System.Threading.Tasks.Task<ConsolaNetReader.CalixtaServices.Saldos[]> ConsultaSaldoAsync(int idCliente, string email, string password) {
            return base.Channel.ConsultaSaldoAsync(idCliente, email, password);
        }
    }
}
