
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class AtmDetails implements Serializable {
  private String bankName;
  private String locationId;
  private String transactionId;
  public String getBankName(){
    return this.bankName;
  }
  public void setBankName(String bankName ){
    this.bankName=bankName;
  }
  public String getLocationId(){
    return this.locationId;
  }
  public void setLocationId(String locationId ){
    this.locationId=locationId;
  }
  public String getTransactionId(){
    return this.transactionId;
  }
  public void setTransactionId(String transactionId ){
    this.transactionId=transactionId;
  }
}
