
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class AuthorizePurchaseDock_values implements Serializable {
  private String source_currency_code;
  private String settlement_currency_code;
  private String billing_currency_code;
  private String source_value;
  private String settlement_value;
  private String billing_value;
  private String billing_conversion_rate;
  private String cash_back_value;
  private String credit_line_usage_fee;
  public String getSource_currency_code(){
    return this.source_currency_code;
  }
  public void setSource_currency_code(String source_currency_code ){
    this.source_currency_code=source_currency_code;
  }
  public String getSettlement_currency_code(){
    return this.settlement_currency_code;
  }
  public void setSettlement_currency_code(String settlement_currency_code ){
    this.settlement_currency_code=settlement_currency_code;
  }
  public String getBilling_currency_code(){
    return this.billing_currency_code;
  }
  public void setBilling_currency_code(String billing_currency_code ){
    this.billing_currency_code=billing_currency_code;
  }
  public String getSource_value(){
    return this.source_value;
  }
  public void setSource_value(String source_value ){
    this.source_value=source_value;
  }
  public String getSettlement_value(){
    return this.settlement_value;
  }
  public void setSettlement_value(String settlement_value ){
    this.settlement_value=settlement_value;
  }
  public String getBilling_value(){
    return this.billing_value;
  }
  public void setBilling_value(String billing_value ){
    this.billing_value=billing_value;
  }
  public String getBilling_conversion_rate(){
    return this.billing_conversion_rate;
  }
  public void setBilling_conversion_rate(String billing_conversion_rate ){
    this.billing_conversion_rate=billing_conversion_rate;
  }
  public String getCash_back_value(){
    return this.cash_back_value;
  }
  public void setCash_back_value(String cash_back_value ){
    this.cash_back_value=cash_back_value;
  }
  public String getCredit_line_usage_fee(){
    return this.credit_line_usage_fee;
  }
  public void setCredit_line_usage_fee(String credit_line_usage_fee ){
    this.credit_line_usage_fee=credit_line_usage_fee;
  }
}
