
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class Beneficiaries implements Serializable {
  private String names;
  private String lastName;
  private String secondLastName;
  private java.util.Calendar birthDate;
  private String relationship;
  private String phoneNumber;
  private String zipcode;
  private String province;
  private String city;
  private String colony;
  private String location;
  private String street;
  private String externalNumber;
  private String internalNumber;
  private Integer percentage;
  public String getNames(){
    return this.names;
  }
  public void setNames(String names ){
    this.names=names;
  }
  public String getLastName(){
    return this.lastName;
  }
  public void setLastName(String lastName ){
    this.lastName=lastName;
  }
  public String getSecondLastName(){
    return this.secondLastName;
  }
  public void setSecondLastName(String secondLastName ){
    this.secondLastName=secondLastName;
  }
  public java.util.Calendar getBirthDate(){
    return this.birthDate;
  }
  public void setBirthDate(java.util.Calendar birthDate ){
    this.birthDate=birthDate;
  }
  public String getRelationship(){
    return this.relationship;
  }
  public void setRelationship(String relationship ){
    this.relationship=relationship;
  }
  public String getPhoneNumber(){
    return this.phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber ){
    this.phoneNumber=phoneNumber;
  }
  public String getZipcode(){
    return this.zipcode;
  }
  public void setZipcode(String zipcode ){
    this.zipcode=zipcode;
  }
  public String getProvince(){
    return this.province;
  }
  public void setProvince(String province ){
    this.province=province;
  }
  public String getCity(){
    return this.city;
  }
  public void setCity(String city ){
    this.city=city;
  }
  public String getColony(){
    return this.colony;
  }
  public void setColony(String colony ){
    this.colony=colony;
  }
  public String getLocation(){
    return this.location;
  }
  public void setLocation(String location ){
    this.location=location;
  }
  public String getStreet(){
    return this.street;
  }
  public void setStreet(String street ){
    this.street=street;
  }
  public String getExternalNumber(){
    return this.externalNumber;
  }
  public void setExternalNumber(String externalNumber ){
    this.externalNumber=externalNumber;
  }
  public String getInternalNumber(){
    return this.internalNumber;
  }
  public void setInternalNumber(String internalNumber ){
    this.internalNumber=internalNumber;
  }
  public Integer getPercentage(){
    return this.percentage;
  }
  public void setPercentage(Integer percentage ){
    this.percentage=percentage;
  }
}
