
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class CardApplicationResponse implements Serializable {
  private String cardId;
  private String personId;
  private String accountId;
  private String assignmentDate;
  private Boolean success;
  private Response response;
  public String getCardId(){
    return this.cardId;
  }
  public void setCardId(String cardId ){
    this.cardId=cardId;
  }
  public String getPersonId(){
    return this.personId;
  }
  public void setPersonId(String personId ){
    this.personId=personId;
  }
  public String getAccountId(){
    return this.accountId;
  }
  public void setAccountId(String accountId ){
    this.accountId=accountId;
  }
  public String getAssignmentDate(){
    return this.assignmentDate;
  }
  public void setAssignmentDate(String assignmentDate ){
    this.assignmentDate=assignmentDate;
  }
  public Boolean isSuccess(){
    return this.success;
  }
  public void setSuccess(Boolean success ){
    this.success=success;
  }
  public Response responseInstance(){
	if(this.response==null){
	this.response=new Response();
	}
	return this.response;
  }
  public Response getResponse(){
    return this.response;
  }
  public void setResponse(Response response ){
    this.response=response;
  }
}
