
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class CreateCustomerRequest implements Serializable {
  private Integer externalCustomerId;
  private String firtname;
  private String secondName;
  private String lastName;
  private String secondLastName;
  private String idNumber;
  private String idType;
  private java.util.Calendar birthDate;
  private java.util.Calendar validityDate;
  private String gender;
  private String email;
  private String identificationType;
  private String identificationNumber;
  private String phoneCode;
  private String phoneNumber;
  private String country;
  private String zipcode;
  private String province;
  private String city;
  private String subdivisioncode;
  private String townCode;
  private String street;
  private String externalNumber;
  private String internalNumber;
  private String referenceAddress;
  private String timeCurrentRecide;
  private String addressTypeCode;
  private String propertyTypeCode;
  private String anotherAddress;
  private String nationality;
  private String countryBirth;
  private String proviceBirth;
  private String occupation;
  private String activity;
  private String incomeLevel;
  private String legalIncomeSource;
  private String noConnectionIllegalNetworks;
  private String companyName;
  private String incomeLevelEntity;
  private String otherMexicanAccount;
  private String paymentCard;
  private String paymentRecharge;
  private String provisionCash;
  private String electronicTransfer;
  private String averageBalance;
  private String amountTransaction;
  private String numberTransaction;
  private String geolocalizationLongitude;
  private String geolocalizationLatitude;
  private String isMati;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getFirtname(){
    return this.firtname;
  }
  public void setFirtname(String firtname ){
    this.firtname=firtname;
  }
  public String getSecondName(){
    return this.secondName;
  }
  public void setSecondName(String secondName ){
    this.secondName=secondName;
  }
  public String getLastName(){
    return this.lastName;
  }
  public void setLastName(String lastName ){
    this.lastName=lastName;
  }
  public String getSecondLastName(){
    return this.secondLastName;
  }
  public void setSecondLastName(String secondLastName ){
    this.secondLastName=secondLastName;
  }
  public String getIdNumber(){
    return this.idNumber;
  }
  public void setIdNumber(String idNumber ){
    this.idNumber=idNumber;
  }
  public String getIdType(){
    return this.idType;
  }
  public void setIdType(String idType ){
    this.idType=idType;
  }
  public java.util.Calendar getBirthDate(){
    return this.birthDate;
  }
  public void setBirthDate(java.util.Calendar birthDate ){
    this.birthDate=birthDate;
  }
  public java.util.Calendar getValidityDate(){
    return this.validityDate;
  }
  public void setValidityDate(java.util.Calendar validityDate ){
    this.validityDate=validityDate;
  }
  public String getGender(){
    return this.gender;
  }
  public void setGender(String gender ){
    this.gender=gender;
  }
  public String getEmail(){
    return this.email;
  }
  public void setEmail(String email ){
    this.email=email;
  }
  public String getIdentificationType(){
    return this.identificationType;
  }
  public void setIdentificationType(String identificationType ){
    this.identificationType=identificationType;
  }
  public String getIdentificationNumber(){
    return this.identificationNumber;
  }
  public void setIdentificationNumber(String identificationNumber ){
    this.identificationNumber=identificationNumber;
  }
  public String getPhoneCode(){
    return this.phoneCode;
  }
  public void setPhoneCode(String phoneCode ){
    this.phoneCode=phoneCode;
  }
  public String getPhoneNumber(){
    return this.phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber ){
    this.phoneNumber=phoneNumber;
  }
  public String getCountry(){
    return this.country;
  }
  public void setCountry(String country ){
    this.country=country;
  }
  public String getZipcode(){
    return this.zipcode;
  }
  public void setZipcode(String zipcode ){
    this.zipcode=zipcode;
  }
  public String getProvince(){
    return this.province;
  }
  public void setProvince(String province ){
    this.province=province;
  }
  public String getCity(){
    return this.city;
  }
  public void setCity(String city ){
    this.city=city;
  }
  public String getSubdivisioncode(){
    return this.subdivisioncode;
  }
  public void setSubdivisioncode(String subdivisioncode ){
    this.subdivisioncode=subdivisioncode;
  }
  public String getTownCode(){
    return this.townCode;
  }
  public void setTownCode(String townCode ){
    this.townCode=townCode;
  }
  public String getStreet(){
    return this.street;
  }
  public void setStreet(String street ){
    this.street=street;
  }
  public String getExternalNumber(){
    return this.externalNumber;
  }
  public void setExternalNumber(String externalNumber ){
    this.externalNumber=externalNumber;
  }
  public String getInternalNumber(){
    return this.internalNumber;
  }
  public void setInternalNumber(String internalNumber ){
    this.internalNumber=internalNumber;
  }
  public String getReferenceAddress(){
    return this.referenceAddress;
  }
  public void setReferenceAddress(String referenceAddress ){
    this.referenceAddress=referenceAddress;
  }
  public String getTimeCurrentRecide(){
    return this.timeCurrentRecide;
  }
  public void setTimeCurrentRecide(String timeCurrentRecide ){
    this.timeCurrentRecide=timeCurrentRecide;
  }
  public String getAddressTypeCode(){
    return this.addressTypeCode;
  }
  public void setAddressTypeCode(String addressTypeCode ){
    this.addressTypeCode=addressTypeCode;
  }
  public String getPropertyTypeCode(){
    return this.propertyTypeCode;
  }
  public void setPropertyTypeCode(String propertyTypeCode ){
    this.propertyTypeCode=propertyTypeCode;
  }
  public String getAnotherAddress(){
    return this.anotherAddress;
  }
  public void setAnotherAddress(String anotherAddress ){
    this.anotherAddress=anotherAddress;
  }
  public String getNationality(){
    return this.nationality;
  }
  public void setNationality(String nationality ){
    this.nationality=nationality;
  }
  public String getCountryBirth(){
    return this.countryBirth;
  }
  public void setCountryBirth(String countryBirth ){
    this.countryBirth=countryBirth;
  }
  public String getProviceBirth(){
    return this.proviceBirth;
  }
  public void setProviceBirth(String proviceBirth ){
    this.proviceBirth=proviceBirth;
  }
  public String getOccupation(){
    return this.occupation;
  }
  public void setOccupation(String occupation ){
    this.occupation=occupation;
  }
  public String getActivity(){
    return this.activity;
  }
  public void setActivity(String activity ){
    this.activity=activity;
  }
  public String getIncomeLevel(){
    return this.incomeLevel;
  }
  public void setIncomeLevel(String incomeLevel ){
    this.incomeLevel=incomeLevel;
  }
  public String getLegalIncomeSource(){
    return this.legalIncomeSource;
  }
  public void setLegalIncomeSource(String legalIncomeSource ){
    this.legalIncomeSource=legalIncomeSource;
  }
  public String getNoConnectionIllegalNetworks(){
    return this.noConnectionIllegalNetworks;
  }
  public void setNoConnectionIllegalNetworks(String noConnectionIllegalNetworks ){
    this.noConnectionIllegalNetworks=noConnectionIllegalNetworks;
  }
  public String getCompanyName(){
    return this.companyName;
  }
  public void setCompanyName(String companyName ){
    this.companyName=companyName;
  }
  public String getIncomeLevelEntity(){
    return this.incomeLevelEntity;
  }
  public void setIncomeLevelEntity(String incomeLevelEntity ){
    this.incomeLevelEntity=incomeLevelEntity;
  }
  public String getOtherMexicanAccount(){
    return this.otherMexicanAccount;
  }
  public void setOtherMexicanAccount(String otherMexicanAccount ){
    this.otherMexicanAccount=otherMexicanAccount;
  }
  public String getPaymentCard(){
    return this.paymentCard;
  }
  public void setPaymentCard(String paymentCard ){
    this.paymentCard=paymentCard;
  }
  public String getPaymentRecharge(){
    return this.paymentRecharge;
  }
  public void setPaymentRecharge(String paymentRecharge ){
    this.paymentRecharge=paymentRecharge;
  }
  public String getProvisionCash(){
    return this.provisionCash;
  }
  public void setProvisionCash(String provisionCash ){
    this.provisionCash=provisionCash;
  }
  public String getElectronicTransfer(){
    return this.electronicTransfer;
  }
  public void setElectronicTransfer(String electronicTransfer ){
    this.electronicTransfer=electronicTransfer;
  }
  public String getAverageBalance(){
    return this.averageBalance;
  }
  public void setAverageBalance(String averageBalance ){
    this.averageBalance=averageBalance;
  }
  public String getAmountTransaction(){
    return this.amountTransaction;
  }
  public void setAmountTransaction(String amountTransaction ){
    this.amountTransaction=amountTransaction;
  }
  public String getNumberTransaction(){
    return this.numberTransaction;
  }
  public void setNumberTransaction(String numberTransaction ){
    this.numberTransaction=numberTransaction;
  }
  public String getGeolocalizationLongitude(){
    return this.geolocalizationLongitude;
  }
  public void setGeolocalizationLongitude(String geolocalizationLongitude ){
    this.geolocalizationLongitude=geolocalizationLongitude;
  }
  public String getGeolocalizationLatitude(){
    return this.geolocalizationLatitude;
  }
  public void setGeolocalizationLatitude(String geolocalizationLatitude ){
    this.geolocalizationLatitude=geolocalizationLatitude;
  }
  public String getIsMati(){
    return this.isMati;
  }
  public void setIsMati(String isMati ){
    this.isMati=isMati;
  }
}
