
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class DebitAccountRequest implements Serializable {
  private Integer externalCustomerId;
  private String accountNumber;
  private java.math.BigDecimal amount;
  private String referenceNumber;
  private Integer originCode;
  private String debitReason;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getAccountNumber(){
    return this.accountNumber;
  }
  public void setAccountNumber(String accountNumber ){
    this.accountNumber=accountNumber;
  }
  public java.math.BigDecimal getAmount(){
    return this.amount;
  }
  public void setAmount(java.math.BigDecimal amount ){
    this.amount=amount;
  }
  public String getReferenceNumber(){
    return this.referenceNumber;
  }
  public void setReferenceNumber(String referenceNumber ){
    this.referenceNumber=referenceNumber;
  }
  public Integer getOriginCode(){
    return this.originCode;
  }
  public void setOriginCode(Integer originCode ){
    this.originCode=originCode;
  }
  public String getDebitReason(){
    return this.debitReason;
  }
  public void setDebitReason(String debitReason ){
    this.debitReason=debitReason;
  }
}
