
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class PurchaseDock_transaction_indicators implements Serializable {
  private Boolean card_present;
  private Boolean cardholder_present;
  private Boolean password_present;
  private Boolean cvv1_present;
  private Boolean cvv2_present;
  private Boolean cvv3_present;
  private Boolean token_present;
  private Boolean is_3ds_present;
  private Boolean is_3ds_valid;
  private Boolean recurring;
  private Boolean allows_partial_approval;
  private Boolean pin_validated_offline;
  private Boolean partially_reversed;
  private Boolean preauthorization;
  private Boolean is_crossborder;
  private Boolean is_dcc;
  private Boolean only_supports_purchase;
  private Boolean is_international;
  private Boolean is_funds_transfer;
  private Boolean is_automated_fuel_dispenser;
  public Boolean isCard_present(){
    return this.card_present;
  }
  public void setCard_present(Boolean card_present ){
    this.card_present=card_present;
  }
  public Boolean isCardholder_present(){
    return this.cardholder_present;
  }
  public void setCardholder_present(Boolean cardholder_present ){
    this.cardholder_present=cardholder_present;
  }
  public Boolean isPassword_present(){
    return this.password_present;
  }
  public void setPassword_present(Boolean password_present ){
    this.password_present=password_present;
  }
  public Boolean isCvv1_present(){
    return this.cvv1_present;
  }
  public void setCvv1_present(Boolean cvv1_present ){
    this.cvv1_present=cvv1_present;
  }
  public Boolean isCvv2_present(){
    return this.cvv2_present;
  }
  public void setCvv2_present(Boolean cvv2_present ){
    this.cvv2_present=cvv2_present;
  }
  public Boolean isCvv3_present(){
    return this.cvv3_present;
  }
  public void setCvv3_present(Boolean cvv3_present ){
    this.cvv3_present=cvv3_present;
  }
  public Boolean isToken_present(){
    return this.token_present;
  }
  public void setToken_present(Boolean token_present ){
    this.token_present=token_present;
  }
  public Boolean isIs_3ds_present(){
    return this.is_3ds_present;
  }
  public void setIs_3ds_present(Boolean is_3ds_present ){
    this.is_3ds_present=is_3ds_present;
  }
  public Boolean isIs_3ds_valid(){
    return this.is_3ds_valid;
  }
  public void setIs_3ds_valid(Boolean is_3ds_valid ){
    this.is_3ds_valid=is_3ds_valid;
  }
  public Boolean isRecurring(){
    return this.recurring;
  }
  public void setRecurring(Boolean recurring ){
    this.recurring=recurring;
  }
  public Boolean isAllows_partial_approval(){
    return this.allows_partial_approval;
  }
  public void setAllows_partial_approval(Boolean allows_partial_approval ){
    this.allows_partial_approval=allows_partial_approval;
  }
  public Boolean isPin_validated_offline(){
    return this.pin_validated_offline;
  }
  public void setPin_validated_offline(Boolean pin_validated_offline ){
    this.pin_validated_offline=pin_validated_offline;
  }
  public Boolean isPartially_reversed(){
    return this.partially_reversed;
  }
  public void setPartially_reversed(Boolean partially_reversed ){
    this.partially_reversed=partially_reversed;
  }
  public Boolean isPreauthorization(){
    return this.preauthorization;
  }
  public void setPreauthorization(Boolean preauthorization ){
    this.preauthorization=preauthorization;
  }
  public Boolean isIs_crossborder(){
    return this.is_crossborder;
  }
  public void setIs_crossborder(Boolean is_crossborder ){
    this.is_crossborder=is_crossborder;
  }
  public Boolean isIs_dcc(){
    return this.is_dcc;
  }
  public void setIs_dcc(Boolean is_dcc ){
    this.is_dcc=is_dcc;
  }
  public Boolean isOnly_supports_purchase(){
    return this.only_supports_purchase;
  }
  public void setOnly_supports_purchase(Boolean only_supports_purchase ){
    this.only_supports_purchase=only_supports_purchase;
  }
  public Boolean isIs_international(){
    return this.is_international;
  }
  public void setIs_international(Boolean is_international ){
    this.is_international=is_international;
  }
  public Boolean isIs_funds_transfer(){
    return this.is_funds_transfer;
  }
  public void setIs_funds_transfer(Boolean is_funds_transfer ){
    this.is_funds_transfer=is_funds_transfer;
  }
  public Boolean isIs_automated_fuel_dispenser(){
    return this.is_automated_fuel_dispenser;
  }
  public void setIs_automated_fuel_dispenser(Boolean is_automated_fuel_dispenser ){
    this.is_automated_fuel_dispenser=is_automated_fuel_dispenser;
  }
}
