
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestGetClientLimits implements Serializable {
  private Integer externalCustomerId;
  private String transactionType;
  private String transactionSubType;
  private Integer accountNumber;
  private String limitType;
  private ConfiguredLimit limit;
  private String operation;
  private String contactId;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getTransactionType(){
    return this.transactionType;
  }
  public void setTransactionType(String transactionType ){
    this.transactionType=transactionType;
  }
  public String getTransactionSubType(){
    return this.transactionSubType;
  }
  public void setTransactionSubType(String transactionSubType ){
    this.transactionSubType=transactionSubType;
  }
  public Integer getAccountNumber(){
    return this.accountNumber;
  }
  public void setAccountNumber(Integer accountNumber ){
    this.accountNumber=accountNumber;
  }
  public String getLimitType(){
    return this.limitType;
  }
  public void setLimitType(String limitType ){
    this.limitType=limitType;
  }
  public ConfiguredLimit limitInstance(){
	if(this.limit==null){
	this.limit=new ConfiguredLimit();
	}
	return this.limit;
  }
  public ConfiguredLimit getLimit(){
    return this.limit;
  }
  public void setLimit(ConfiguredLimit limit ){
    this.limit=limit;
  }
  public String getOperation(){
    return this.operation;
  }
  public void setOperation(String operation ){
    this.operation=operation;
  }
  public String getContactId(){
    return this.contactId;
  }
  public void setContactId(String contactId ){
    this.contactId=contactId;
  }
}
