
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestAuthorizePurchase implements Serializable {
  private Integer externalCustomerId;
  private String uuid;
  private String accountNumber;
  private String transmissionDateTimeGmt;
  private String date;
  private String time;
  private String mti;
  private Processing processing;
  private String nsu;
  private String cardExpirationDate;
  private CardEntry cardEntry;
  private String merchantCategoryCode;
  private Values values;
  private String institutionName;
  private String terminalCode;
  private String retrievalReferenceNumber;
  private String acquirerCountryCode;
  private TransactionIndicators transactionIndicators;
  private Tokens62 tokens62;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getUuid(){
    return this.uuid;
  }
  public void setUuid(String uuid ){
    this.uuid=uuid;
  }
  public String getAccountNumber(){
    return this.accountNumber;
  }
  public void setAccountNumber(String accountNumber ){
    this.accountNumber=accountNumber;
  }
  public String getTransmissionDateTimeGmt(){
    return this.transmissionDateTimeGmt;
  }
  public void setTransmissionDateTimeGmt(String transmissionDateTimeGmt ){
    this.transmissionDateTimeGmt=transmissionDateTimeGmt;
  }
  public String getDate(){
    return this.date;
  }
  public void setDate(String date ){
    this.date=date;
  }
  public String getTime(){
    return this.time;
  }
  public void setTime(String time ){
    this.time=time;
  }
  public String getMti(){
    return this.mti;
  }
  public void setMti(String mti ){
    this.mti=mti;
  }
  public Processing processingInstance(){
	if(this.processing==null){
	this.processing=new Processing();
	}
	return this.processing;
  }
  public Processing getProcessing(){
    return this.processing;
  }
  public void setProcessing(Processing processing ){
    this.processing=processing;
  }
  public String getNsu(){
    return this.nsu;
  }
  public void setNsu(String nsu ){
    this.nsu=nsu;
  }
  public String getCardExpirationDate(){
    return this.cardExpirationDate;
  }
  public void setCardExpirationDate(String cardExpirationDate ){
    this.cardExpirationDate=cardExpirationDate;
  }
  public CardEntry cardEntryInstance(){
	if(this.cardEntry==null){
	this.cardEntry=new CardEntry();
	}
	return this.cardEntry;
  }
  public CardEntry getCardEntry(){
    return this.cardEntry;
  }
  public void setCardEntry(CardEntry cardEntry ){
    this.cardEntry=cardEntry;
  }
  public String getMerchantCategoryCode(){
    return this.merchantCategoryCode;
  }
  public void setMerchantCategoryCode(String merchantCategoryCode ){
    this.merchantCategoryCode=merchantCategoryCode;
  }
  public Values valuesInstance(){
	if(this.values==null){
	this.values=new Values();
	}
	return this.values;
  }
  public Values getValues(){
    return this.values;
  }
  public void setValues(Values values ){
    this.values=values;
  }
  public String getInstitutionName(){
    return this.institutionName;
  }
  public void setInstitutionName(String institutionName ){
    this.institutionName=institutionName;
  }
  public String getTerminalCode(){
    return this.terminalCode;
  }
  public void setTerminalCode(String terminalCode ){
    this.terminalCode=terminalCode;
  }
  public String getRetrievalReferenceNumber(){
    return this.retrievalReferenceNumber;
  }
  public void setRetrievalReferenceNumber(String retrievalReferenceNumber ){
    this.retrievalReferenceNumber=retrievalReferenceNumber;
  }
  public String getAcquirerCountryCode(){
    return this.acquirerCountryCode;
  }
  public void setAcquirerCountryCode(String acquirerCountryCode ){
    this.acquirerCountryCode=acquirerCountryCode;
  }
  public TransactionIndicators transactionIndicatorsInstance(){
	if(this.transactionIndicators==null){
	this.transactionIndicators=new TransactionIndicators();
	}
	return this.transactionIndicators;
  }
  public TransactionIndicators getTransactionIndicators(){
    return this.transactionIndicators;
  }
  public void setTransactionIndicators(TransactionIndicators transactionIndicators ){
    this.transactionIndicators=transactionIndicators;
  }
  public Tokens62 tokens62Instance(){
	if(this.tokens62==null){
	this.tokens62=new Tokens62();
	}
	return this.tokens62;
  }
  public Tokens62 getTokens62(){
    return this.tokens62;
  }
  public void setTokens62(Tokens62 tokens62 ){
    this.tokens62=tokens62;
  }
}
