
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestRegisterAccount implements Serializable {
  private String transactionType;
  private String transactionSubType;
  private Integer externalCustomerId;
  private String accountNumber;
  private RequestRegisterAccount_creditorAccount creditorAccount;
  private String otpCode;
  private String additionalData;
  public String getTransactionType(){
    return this.transactionType;
  }
  public void setTransactionType(String transactionType ){
    this.transactionType=transactionType;
  }
  public String getTransactionSubType(){
    return this.transactionSubType;
  }
  public void setTransactionSubType(String transactionSubType ){
    this.transactionSubType=transactionSubType;
  }
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getAccountNumber(){
    return this.accountNumber;
  }
  public void setAccountNumber(String accountNumber ){
    this.accountNumber=accountNumber;
  }
  public RequestRegisterAccount_creditorAccount creditorAccountInstance(){
	if(this.creditorAccount==null){
	this.creditorAccount=new RequestRegisterAccount_creditorAccount();
	}
	return this.creditorAccount;
  }
  public RequestRegisterAccount_creditorAccount getCreditorAccount(){
    return this.creditorAccount;
  }
  public void setCreditorAccount(RequestRegisterAccount_creditorAccount creditorAccount ){
    this.creditorAccount=creditorAccount;
  }
  public String getOtpCode(){
    return this.otpCode;
  }
  public void setOtpCode(String otpCode ){
    this.otpCode=otpCode;
  }
  public String getAdditionalData(){
    return this.additionalData;
  }
  public void setAdditionalData(String additionalData ){
    this.additionalData=additionalData;
  }
}
