
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestValidateAllSecurityQA implements Serializable {
  private Integer externalCustomerId;
  private CstmrVal1 cstmrVal1;
  private CstmrVal2 cstmrVal2;
  private CstmrVal3 cstmrVal3;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public CstmrVal1 cstmrVal1Instance(){
	if(this.cstmrVal1==null){
	this.cstmrVal1=new CstmrVal1();
	}
	return this.cstmrVal1;
  }
  public CstmrVal1 getCstmrVal1(){
    return this.cstmrVal1;
  }
  public void setCstmrVal1(CstmrVal1 cstmrVal1 ){
    this.cstmrVal1=cstmrVal1;
  }
  public CstmrVal2 cstmrVal2Instance(){
	if(this.cstmrVal2==null){
	this.cstmrVal2=new CstmrVal2();
	}
	return this.cstmrVal2;
  }
  public CstmrVal2 getCstmrVal2(){
    return this.cstmrVal2;
  }
  public void setCstmrVal2(CstmrVal2 cstmrVal2 ){
    this.cstmrVal2=cstmrVal2;
  }
  public CstmrVal3 cstmrVal3Instance(){
	if(this.cstmrVal3==null){
	this.cstmrVal3=new CstmrVal3();
	}
	return this.cstmrVal3;
  }
  public CstmrVal3 getCstmrVal3(){
    return this.cstmrVal3;
  }
  public void setCstmrVal3(CstmrVal3 cstmrVal3 ){
    this.cstmrVal3=cstmrVal3;
  }
}
