
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestRegisterAccountSpei implements Serializable {
  private String accountNumber;
  private String accountNumberDestination;
  private Integer typeDestinationId;
  private Integer externalCustomerId;
  private int bankId;
  private String productAlias;
  public String getAccountNumber(){
    return this.accountNumber;
  }
  public void setAccountNumber(String accountNumber ){
    this.accountNumber=accountNumber;
  }
  public String getAccountNumberDestination(){
    return this.accountNumberDestination;
  }
  public void setAccountNumberDestination(String accountNumberDestination ){
    this.accountNumberDestination=accountNumberDestination;
  }
  public Integer getTypeDestinationId(){
    return this.typeDestinationId;
  }
  public void setTypeDestinationId(Integer typeDestinationId ){
    this.typeDestinationId=typeDestinationId;
  }
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public int getBankId(){
    return this.bankId;
  }
  public void setBankId(int bankId ){
    this.bankId=bankId;
  }
  public String getProductAlias(){
    return this.productAlias;
  }
  public void setProductAlias(String productAlias ){
    this.productAlias=productAlias;
  }
}
