
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestTransferSpi implements Serializable {
  private Integer externalCustomerId;
  private String originAccountNumber;
  private String destinationAccountNumber;
  private String originAccountAlias;
  private String destinationAccountAlias;
  private String destinationBeneficiaryName;
  private Integer amount;
  private String description;
  private String bankId;
  private String bankName;
  private String destinationAccountOwnerName;
  private Integer destinationTypeAccount;
  private String ownerName;
  private String detail;
  private java.math.BigDecimal commission;
  private java.math.BigDecimal latitude;
  private java.math.BigDecimal longitude;
  private String referenceNumber;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getOriginAccountNumber(){
    return this.originAccountNumber;
  }
  public void setOriginAccountNumber(String originAccountNumber ){
    this.originAccountNumber=originAccountNumber;
  }
  public String getDestinationAccountNumber(){
    return this.destinationAccountNumber;
  }
  public void setDestinationAccountNumber(String destinationAccountNumber ){
    this.destinationAccountNumber=destinationAccountNumber;
  }
  public String getOriginAccountAlias(){
    return this.originAccountAlias;
  }
  public void setOriginAccountAlias(String originAccountAlias ){
    this.originAccountAlias=originAccountAlias;
  }
  public String getDestinationAccountAlias(){
    return this.destinationAccountAlias;
  }
  public void setDestinationAccountAlias(String destinationAccountAlias ){
    this.destinationAccountAlias=destinationAccountAlias;
  }
  public String getDestinationBeneficiaryName(){
    return this.destinationBeneficiaryName;
  }
  public void setDestinationBeneficiaryName(String destinationBeneficiaryName ){
    this.destinationBeneficiaryName=destinationBeneficiaryName;
  }
  public Integer getAmount(){
    return this.amount;
  }
  public void setAmount(Integer amount ){
    this.amount=amount;
  }
  public String getDescription(){
    return this.description;
  }
  public void setDescription(String description ){
    this.description=description;
  }
  public String getBankId(){
    return this.bankId;
  }
  public void setBankId(String bankId ){
    this.bankId=bankId;
  }
  public String getBankName(){
    return this.bankName;
  }
  public void setBankName(String bankName ){
    this.bankName=bankName;
  }
  public String getDestinationAccountOwnerName(){
    return this.destinationAccountOwnerName;
  }
  public void setDestinationAccountOwnerName(String destinationAccountOwnerName ){
    this.destinationAccountOwnerName=destinationAccountOwnerName;
  }
  public Integer getDestinationTypeAccount(){
    return this.destinationTypeAccount;
  }
  public void setDestinationTypeAccount(Integer destinationTypeAccount ){
    this.destinationTypeAccount=destinationTypeAccount;
  }
  public String getOwnerName(){
    return this.ownerName;
  }
  public void setOwnerName(String ownerName ){
    this.ownerName=ownerName;
  }
  public String getDetail(){
    return this.detail;
  }
  public void setDetail(String detail ){
    this.detail=detail;
  }
  public java.math.BigDecimal getCommission(){
    return this.commission;
  }
  public void setCommission(java.math.BigDecimal commission ){
    this.commission=commission;
  }
  public java.math.BigDecimal getLatitude(){
    return this.latitude;
  }
  public void setLatitude(java.math.BigDecimal latitude ){
    this.latitude=latitude;
  }
  public java.math.BigDecimal getLongitude(){
    return this.longitude;
  }
  public void setLongitude(java.math.BigDecimal longitude ){
    this.longitude=longitude;
  }
  public String getReferenceNumber(){
    return this.referenceNumber;
  }
  public void setReferenceNumber(String referenceNumber ){
    this.referenceNumber=referenceNumber;
  }
}
