
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestAuthorizeReversalDock implements Serializable {
  private String account_id;
  private String person_id;
  private String card_id;
  private String product_id;
  private String product_status;
  private String bank_branch_number;
  private String bank_account_number;
  private String transmission_date_time_gmt;
  private String terminal_date;
  private String terminal_time;
  private String mti;
  private Reversal_processing processing;
  private String nsu;
  private String authorization_code;
  private String card_number;
  private String card_expiration_date;
  private String transaction_origin;
  private Integer installments;
  private String installment_type;
  private Reversal_card_entry card_entry;
  private String merchant_category_code;
  private Reversal_values values;
  private String establishment;
  private String terminal_code;
  private String establishment_code;
  private String retrieval_reference_number;
  private String advice_reason;
  private String advice_reason_code;
  private String pos_postal_code;
  private String acquirer_country_code;
  private Reversal_preauthorization preauthorization;
  private Tokens_62 tokens_62;
  private Reversal_token_data token_data;
  private Reversal_funds_transfer funds_transfer;
  private Reversal_transaction_indicators transaction_indicators;
  private Reversal_original_transaction_data original_transaction_data;
  private String additional_information;
  private Reversal_exchange_rate exchange_rate;
  private Reversal_installment_data installment_data;
  public String getAccount_id(){
    return this.account_id;
  }
  public void setAccount_id(String account_id ){
    this.account_id=account_id;
  }
  public String getPerson_id(){
    return this.person_id;
  }
  public void setPerson_id(String person_id ){
    this.person_id=person_id;
  }
  public String getCard_id(){
    return this.card_id;
  }
  public void setCard_id(String card_id ){
    this.card_id=card_id;
  }
  public String getProduct_id(){
    return this.product_id;
  }
  public void setProduct_id(String product_id ){
    this.product_id=product_id;
  }
  public String getProduct_status(){
    return this.product_status;
  }
  public void setProduct_status(String product_status ){
    this.product_status=product_status;
  }
  public String getBank_branch_number(){
    return this.bank_branch_number;
  }
  public void setBank_branch_number(String bank_branch_number ){
    this.bank_branch_number=bank_branch_number;
  }
  public String getBank_account_number(){
    return this.bank_account_number;
  }
  public void setBank_account_number(String bank_account_number ){
    this.bank_account_number=bank_account_number;
  }
  public String getTransmission_date_time_gmt(){
    return this.transmission_date_time_gmt;
  }
  public void setTransmission_date_time_gmt(String transmission_date_time_gmt ){
    this.transmission_date_time_gmt=transmission_date_time_gmt;
  }
  public String getTerminal_date(){
    return this.terminal_date;
  }
  public void setTerminal_date(String terminal_date ){
    this.terminal_date=terminal_date;
  }
  public String getTerminal_time(){
    return this.terminal_time;
  }
  public void setTerminal_time(String terminal_time ){
    this.terminal_time=terminal_time;
  }
  public String getMti(){
    return this.mti;
  }
  public void setMti(String mti ){
    this.mti=mti;
  }
  public Reversal_processing processingInstance(){
	if(this.processing==null){
	this.processing=new Reversal_processing();
	}
	return this.processing;
  }
  public Reversal_processing getProcessing(){
    return this.processing;
  }
  public void setProcessing(Reversal_processing processing ){
    this.processing=processing;
  }
  public String getNsu(){
    return this.nsu;
  }
  public void setNsu(String nsu ){
    this.nsu=nsu;
  }
  public String getAuthorization_code(){
    return this.authorization_code;
  }
  public void setAuthorization_code(String authorization_code ){
    this.authorization_code=authorization_code;
  }
  public String getCard_number(){
    return this.card_number;
  }
  public void setCard_number(String card_number ){
    this.card_number=card_number;
  }
  public String getCard_expiration_date(){
    return this.card_expiration_date;
  }
  public void setCard_expiration_date(String card_expiration_date ){
    this.card_expiration_date=card_expiration_date;
  }
  public String getTransaction_origin(){
    return this.transaction_origin;
  }
  public void setTransaction_origin(String transaction_origin ){
    this.transaction_origin=transaction_origin;
  }
  public Integer getInstallments(){
    return this.installments;
  }
  public void setInstallments(Integer installments ){
    this.installments=installments;
  }
  public String getInstallment_type(){
    return this.installment_type;
  }
  public void setInstallment_type(String installment_type ){
    this.installment_type=installment_type;
  }
  public Reversal_card_entry card_entryInstance(){
	if(this.card_entry==null){
	this.card_entry=new Reversal_card_entry();
	}
	return this.card_entry;
  }
  public Reversal_card_entry getCard_entry(){
    return this.card_entry;
  }
  public void setCard_entry(Reversal_card_entry card_entry ){
    this.card_entry=card_entry;
  }
  public String getMerchant_category_code(){
    return this.merchant_category_code;
  }
  public void setMerchant_category_code(String merchant_category_code ){
    this.merchant_category_code=merchant_category_code;
  }
  public Reversal_values valuesInstance(){
	if(this.values==null){
	this.values=new Reversal_values();
	}
	return this.values;
  }
  public Reversal_values getValues(){
    return this.values;
  }
  public void setValues(Reversal_values values ){
    this.values=values;
  }
  public String getEstablishment(){
    return this.establishment;
  }
  public void setEstablishment(String establishment ){
    this.establishment=establishment;
  }
  public String getTerminal_code(){
    return this.terminal_code;
  }
  public void setTerminal_code(String terminal_code ){
    this.terminal_code=terminal_code;
  }
  public String getEstablishment_code(){
    return this.establishment_code;
  }
  public void setEstablishment_code(String establishment_code ){
    this.establishment_code=establishment_code;
  }
  public String getRetrieval_reference_number(){
    return this.retrieval_reference_number;
  }
  public void setRetrieval_reference_number(String retrieval_reference_number ){
    this.retrieval_reference_number=retrieval_reference_number;
  }
  public String getAdvice_reason(){
    return this.advice_reason;
  }
  public void setAdvice_reason(String advice_reason ){
    this.advice_reason=advice_reason;
  }
  public String getAdvice_reason_code(){
    return this.advice_reason_code;
  }
  public void setAdvice_reason_code(String advice_reason_code ){
    this.advice_reason_code=advice_reason_code;
  }
  public String getPos_postal_code(){
    return this.pos_postal_code;
  }
  public void setPos_postal_code(String pos_postal_code ){
    this.pos_postal_code=pos_postal_code;
  }
  public String getAcquirer_country_code(){
    return this.acquirer_country_code;
  }
  public void setAcquirer_country_code(String acquirer_country_code ){
    this.acquirer_country_code=acquirer_country_code;
  }
  public Reversal_preauthorization preauthorizationInstance(){
	if(this.preauthorization==null){
	this.preauthorization=new Reversal_preauthorization();
	}
	return this.preauthorization;
  }
  public Reversal_preauthorization getPreauthorization(){
    return this.preauthorization;
  }
  public void setPreauthorization(Reversal_preauthorization preauthorization ){
    this.preauthorization=preauthorization;
  }
  public Tokens_62 tokens_62Instance(){
	if(this.tokens_62==null){
	this.tokens_62=new Tokens_62();
	}
	return this.tokens_62;
  }
  public Tokens_62 getTokens_62(){
    return this.tokens_62;
  }
  public void setTokens_62(Tokens_62 tokens_62 ){
    this.tokens_62=tokens_62;
  }
  public Reversal_token_data token_dataInstance(){
	if(this.token_data==null){
	this.token_data=new Reversal_token_data();
	}
	return this.token_data;
  }
  public Reversal_token_data getToken_data(){
    return this.token_data;
  }
  public void setToken_data(Reversal_token_data token_data ){
    this.token_data=token_data;
  }
  public Reversal_funds_transfer funds_transferInstance(){
	if(this.funds_transfer==null){
	this.funds_transfer=new Reversal_funds_transfer();
	}
	return this.funds_transfer;
  }
  public Reversal_funds_transfer getFunds_transfer(){
    return this.funds_transfer;
  }
  public void setFunds_transfer(Reversal_funds_transfer funds_transfer ){
    this.funds_transfer=funds_transfer;
  }
  public Reversal_transaction_indicators transaction_indicatorsInstance(){
	if(this.transaction_indicators==null){
	this.transaction_indicators=new Reversal_transaction_indicators();
	}
	return this.transaction_indicators;
  }
  public Reversal_transaction_indicators getTransaction_indicators(){
    return this.transaction_indicators;
  }
  public void setTransaction_indicators(Reversal_transaction_indicators transaction_indicators ){
    this.transaction_indicators=transaction_indicators;
  }
  public Reversal_original_transaction_data original_transaction_dataInstance(){
	if(this.original_transaction_data==null){
	this.original_transaction_data=new Reversal_original_transaction_data();
	}
	return this.original_transaction_data;
  }
  public Reversal_original_transaction_data getOriginal_transaction_data(){
    return this.original_transaction_data;
  }
  public void setOriginal_transaction_data(Reversal_original_transaction_data original_transaction_data ){
    this.original_transaction_data=original_transaction_data;
  }
  public String getAdditional_information(){
    return this.additional_information;
  }
  public void setAdditional_information(String additional_information ){
    this.additional_information=additional_information;
  }
  public Reversal_exchange_rate exchange_rateInstance(){
	if(this.exchange_rate==null){
	this.exchange_rate=new Reversal_exchange_rate();
	}
	return this.exchange_rate;
  }
  public Reversal_exchange_rate getExchange_rate(){
    return this.exchange_rate;
  }
  public void setExchange_rate(Reversal_exchange_rate exchange_rate ){
    this.exchange_rate=exchange_rate;
  }
  public Reversal_installment_data installment_dataInstance(){
	if(this.installment_data==null){
	this.installment_data=new Reversal_installment_data();
	}
	return this.installment_data;
  }
  public Reversal_installment_data getInstallment_data(){
    return this.installment_data;
  }
  public void setInstallment_data(Reversal_installment_data installment_data ){
    this.installment_data=installment_data;
  }
}
