
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestGetMovementsDetail implements Serializable {
  private Integer externalCustomerId;
  private String accountNumber;
  private Integer numberOfMovements;
  private String minDate;
  private String maxDate;
  private Integer sequential;
  private Integer movementId;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getAccountNumber(){
    return this.accountNumber;
  }
  public void setAccountNumber(String accountNumber ){
    this.accountNumber=accountNumber;
  }
  public Integer getNumberOfMovements(){
    return this.numberOfMovements;
  }
  public void setNumberOfMovements(Integer numberOfMovements ){
    this.numberOfMovements=numberOfMovements;
  }
  public String getMinDate(){
    return this.minDate;
  }
  public void setMinDate(String minDate ){
    this.minDate=minDate;
  }
  public String getMaxDate(){
    return this.maxDate;
  }
  public void setMaxDate(String maxDate ){
    this.maxDate=maxDate;
  }
  public Integer getSequential(){
    return this.sequential;
  }
  public void setSequential(Integer sequential ){
    this.sequential=sequential;
  }
  public Integer getMovementId(){
    return this.movementId;
  }
  public void setMovementId(Integer movementId ){
    this.movementId=movementId;
  }
}
