
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestDefineSecurityQA implements Serializable {
  private Integer externalCustomerId;
  private CstmrAnswer1 cstmrAnswer1;
  private CstmrAnswer2 cstmrAnswer2;
  private CstmrAnswer3 cstmrAnswer3;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public CstmrAnswer1 cstmrAnswer1Instance(){
	if(this.cstmrAnswer1==null){
	this.cstmrAnswer1=new CstmrAnswer1();
	}
	return this.cstmrAnswer1;
  }
  public CstmrAnswer1 getCstmrAnswer1(){
    return this.cstmrAnswer1;
  }
  public void setCstmrAnswer1(CstmrAnswer1 cstmrAnswer1 ){
    this.cstmrAnswer1=cstmrAnswer1;
  }
  public CstmrAnswer2 cstmrAnswer2Instance(){
	if(this.cstmrAnswer2==null){
	this.cstmrAnswer2=new CstmrAnswer2();
	}
	return this.cstmrAnswer2;
  }
  public CstmrAnswer2 getCstmrAnswer2(){
    return this.cstmrAnswer2;
  }
  public void setCstmrAnswer2(CstmrAnswer2 cstmrAnswer2 ){
    this.cstmrAnswer2=cstmrAnswer2;
  }
  public CstmrAnswer3 cstmrAnswer3Instance(){
	if(this.cstmrAnswer3==null){
	this.cstmrAnswer3=new CstmrAnswer3();
	}
	return this.cstmrAnswer3;
  }
  public CstmrAnswer3 getCstmrAnswer3(){
    return this.cstmrAnswer3;
  }
  public void setCstmrAnswer3(CstmrAnswer3 cstmrAnswer3 ){
    this.cstmrAnswer3=cstmrAnswer3;
  }
}
