
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class RequestUpdateProfile implements Serializable {
  private Integer externalCustomerId;
  private String email;
  private String phoneNumber;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getEmail(){
    return this.email;
  }
  public void setEmail(String email ){
    this.email=email;
  }
  public String getPhoneNumber(){
    return this.phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber ){
    this.phoneNumber=phoneNumber;
  }
}
