
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ResponseGetUserEntityInformation implements Serializable {
  private Boolean success;
  private java.util.Calendar registrationDate;
  private java.util.Calendar modifyDate;
  private String completeName;
  private String entityType;
  private String identityCard;
  private String firstSurName;
  private String secondSurName;
  private java.util.Calendar birthDate;
  private String firstName;
  private String secondName;
  private String rFC;
  private String mail;
  private String phoneNumber;
  private String customerLevel;
  private Integer addressId;
  private Message message;
  public Boolean isSuccess(){
    return this.success;
  }
  public void setSuccess(Boolean success ){
    this.success=success;
  }
  public java.util.Calendar getRegistrationDate(){
    return this.registrationDate;
  }
  public void setRegistrationDate(java.util.Calendar registrationDate ){
    this.registrationDate=registrationDate;
  }
  public java.util.Calendar getModifyDate(){
    return this.modifyDate;
  }
  public void setModifyDate(java.util.Calendar modifyDate ){
    this.modifyDate=modifyDate;
  }
  public String getCompleteName(){
    return this.completeName;
  }
  public void setCompleteName(String completeName ){
    this.completeName=completeName;
  }
  public String getEntityType(){
    return this.entityType;
  }
  public void setEntityType(String entityType ){
    this.entityType=entityType;
  }
  public String getIdentityCard(){
    return this.identityCard;
  }
  public void setIdentityCard(String identityCard ){
    this.identityCard=identityCard;
  }
  public String getFirstSurName(){
    return this.firstSurName;
  }
  public void setFirstSurName(String firstSurName ){
    this.firstSurName=firstSurName;
  }
  public String getSecondSurName(){
    return this.secondSurName;
  }
  public void setSecondSurName(String secondSurName ){
    this.secondSurName=secondSurName;
  }
  public java.util.Calendar getBirthDate(){
    return this.birthDate;
  }
  public void setBirthDate(java.util.Calendar birthDate ){
    this.birthDate=birthDate;
  }
  public String getFirstName(){
    return this.firstName;
  }
  public void setFirstName(String firstName ){
    this.firstName=firstName;
  }
  public String getSecondName(){
    return this.secondName;
  }
  public void setSecondName(String secondName ){
    this.secondName=secondName;
  }
  public String getRFC(){
    return this.rFC;
  }
  public void setRFC(String rFC ){
    this.rFC=rFC;
  }
  public String getMail(){
    return this.mail;
  }
  public void setMail(String mail ){
    this.mail=mail;
  }
  public String getPhoneNumber(){
    return this.phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber ){
    this.phoneNumber=phoneNumber;
  }
  public String getCustomerLevel(){
    return this.customerLevel;
  }
  public void setCustomerLevel(String customerLevel ){
    this.customerLevel=customerLevel;
  }
  public Integer getAddressId(){
    return this.addressId;
  }
  public void setAddressId(Integer addressId ){
    this.addressId=addressId;
  }
  public Message messageInstance(){
	if(this.message==null){
	this.message=new Message();
	}
	return this.message;
  }
  public Message getMessage(){
    return this.message;
  }
  public void setMessage(Message message ){
    this.message=message;
  }
}
