
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ResponseAuthorizePurchase implements Serializable {
  private Boolean success;
  private Response response;
  private String transactionStatus;
  private String approvedValue;
  private String settlementValue;
  private String cardholderBillingValue;
  private String reason;
  private String availableLimit;
  public Boolean isSuccess(){
    return this.success;
  }
  public void setSuccess(Boolean success ){
    this.success=success;
  }
  public Response responseInstance(){
	if(this.response==null){
	this.response=new Response();
	}
	return this.response;
  }
  public Response getResponse(){
    return this.response;
  }
  public void setResponse(Response response ){
    this.response=response;
  }
  public String getTransactionStatus(){
    return this.transactionStatus;
  }
  public void setTransactionStatus(String transactionStatus ){
    this.transactionStatus=transactionStatus;
  }
  public String getApprovedValue(){
    return this.approvedValue;
  }
  public void setApprovedValue(String approvedValue ){
    this.approvedValue=approvedValue;
  }
  public String getSettlementValue(){
    return this.settlementValue;
  }
  public void setSettlementValue(String settlementValue ){
    this.settlementValue=settlementValue;
  }
  public String getCardholderBillingValue(){
    return this.cardholderBillingValue;
  }
  public void setCardholderBillingValue(String cardholderBillingValue ){
    this.cardholderBillingValue=cardholderBillingValue;
  }
  public String getReason(){
    return this.reason;
  }
  public void setReason(String reason ){
    this.reason=reason;
  }
  public String getAvailableLimit(){
    return this.availableLimit;
  }
  public void setAvailableLimit(String availableLimit ){
    this.availableLimit=availableLimit;
  }
}
