
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ResponseAuthorizeDepositDock implements Serializable {
  private String approved_value;
  private String settlement_value;
  private String cardholder_billing_value;
  private ArrayList response;
  private String reason;
  private String available_limit;
  private Integer authorization_code;
  private String seq;
  public String getApproved_value(){
    return this.approved_value;
  }
  public void setApproved_value(String approved_value ){
    this.approved_value=approved_value;
  }
  public String getSettlement_value(){
    return this.settlement_value;
  }
  public void setSettlement_value(String settlement_value ){
    this.settlement_value=settlement_value;
  }
  public String getCardholder_billing_value(){
    return this.cardholder_billing_value;
  }
  public void setCardholder_billing_value(String cardholder_billing_value ){
    this.cardholder_billing_value=cardholder_billing_value;
  }
  public ArrayList getResponse(){
    return this.response;
  }
  public void setResponse(ArrayList response ){
    this.response=response;
  }
  public String getReason(){
    return this.reason;
  }
  public void setReason(String reason ){
    this.reason=reason;
  }
  public String getAvailable_limit(){
    return this.available_limit;
  }
  public void setAvailable_limit(String available_limit ){
    this.available_limit=available_limit;
  }
  public Integer getAuthorization_code(){
    return this.authorization_code;
  }
  public void setAuthorization_code(Integer authorization_code ){
    this.authorization_code=authorization_code;
  }
  public String getSeq(){
    return this.seq;
  }
  public void setSeq(String seq ){
    this.seq=seq;
  }
}
