
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ResponseGetBalancesDetail implements Serializable {
  private String success;
  private String accountName;
  private String accountStatus;
  private java.math.BigDecimal availableBalance;
  private java.math.BigDecimal averageBalance;
  private Integer currencyId;
  private String deliveryAddress;
  private Integer freezingsNumber;
  private java.math.BigDecimal frozenAmount;
  private String lastCutoffBalance;
  private String lastOperationDate;
  private String openingDate;
  private java.math.BigDecimal overdraftAmount;
  private Integer productId;
  private java.math.BigDecimal toDrawBalance;
  private java.math.BigDecimal accountingBalance;
  private Integer official;
  private String clabeAccountNumber;
  private Integer idDebitCard;
  private String debitCardNumber;
  private String stateDebitCard;
  private Message message;
  
  public String getSuccess(){
    return this.success;
  }
  public void setSuccess(String success ){
    this.success=success;
  }
  public String getAccountName(){
    return this.accountName;
  }
  public void setAccountName(String accountName ){
    this.accountName=accountName;
  }
  public String getAccountStatus(){
    return this.accountStatus;
  }
  public void setAccountStatus(String accountStatus ){
    this.accountStatus=accountStatus;
  }
  public java.math.BigDecimal getAvailableBalance(){
    return this.availableBalance;
  }
  public void setAvailableBalance(java.math.BigDecimal availableBalance ){
    this.availableBalance=availableBalance;
  }
  public java.math.BigDecimal getAverageBalance(){
    return this.averageBalance;
  }
  public void setAverageBalance(java.math.BigDecimal averageBalance ){
    this.averageBalance=averageBalance;
  }
  public Integer getCurrencyId(){
    return this.currencyId;
  }
  public void setCurrencyId(Integer currencyId ){
    this.currencyId=currencyId;
  }
  public String getDeliveryAddress(){
    return this.deliveryAddress;
  }
  public void setDeliveryAddress(String deliveryAddress ){
    this.deliveryAddress=deliveryAddress;
  }
  public Integer getFreezingsNumber(){
    return this.freezingsNumber;
  }
  public void setFreezingsNumber(Integer freezingsNumber ){
    this.freezingsNumber=freezingsNumber;
  }
  public java.math.BigDecimal getFrozenAmount(){
    return this.frozenAmount;
  }
  public void setFrozenAmount(java.math.BigDecimal frozenAmount ){
    this.frozenAmount=frozenAmount;
  }
  public String getLastCutoffBalance(){
    return this.lastCutoffBalance;
  }
  public void setLastCutoffBalance(String lastCutoffBalance ){
    this.lastCutoffBalance=lastCutoffBalance;
  }
  public String getLastOperationDate(){
    return this.lastOperationDate;
  }
  public void setLastOperationDate(String lastOperationDate ){
    this.lastOperationDate=lastOperationDate;
  }
  public String getOpeningDate(){
    return this.openingDate;
  }
  public void setOpeningDate(String openingDate ){
    this.openingDate=openingDate;
  }
  public java.math.BigDecimal getOverdraftAmount(){
    return this.overdraftAmount;
  }
  public void setOverdraftAmount(java.math.BigDecimal overdraftAmount ){
    this.overdraftAmount=overdraftAmount;
  }
  public Integer getProductId(){
    return this.productId;
  }
  public void setProductId(Integer productId ){
    this.productId=productId;
  }
  public java.math.BigDecimal getToDrawBalance(){
    return this.toDrawBalance;
  }
  public void setToDrawBalance(java.math.BigDecimal toDrawBalance ){
    this.toDrawBalance=toDrawBalance;
  }
  public java.math.BigDecimal getAccountingBalance(){
    return this.accountingBalance;
  }
  public void setAccountingBalance(java.math.BigDecimal accountingBalance ){
    this.accountingBalance=accountingBalance;
  }
  public Integer getOfficial(){
    return this.official;
  }
  public void setOfficial(Integer official ){
    this.official=official;
  }
  public String getClabeAccountNumber(){
    return this.clabeAccountNumber;
  }
  public void setClabeAccountNumber(String clabeAccountNumber ){
    this.clabeAccountNumber=clabeAccountNumber;
  }
  public Integer getIdDebitCard(){
    return this.idDebitCard;
  }
  public void setIdDebitCard(Integer idDebitCard ){
    this.idDebitCard=idDebitCard;
  }
  public String getDebitCardNumber(){
    return this.debitCardNumber;
  }
  public void setDebitCardNumber(String debitCardNumber ){
    this.debitCardNumber=debitCardNumber;
  }
  public String getStateDebitCard(){
    return this.stateDebitCard;
  }
  public void setStateDebitCard(String stateDebitCard ){
    this.stateDebitCard=stateDebitCard;
  }
  public Message messageInstance(){
	if(this.message==null){
	this.message=new Message();
	}
	return this.message;
  }
  public Message getMessage(){
    return this.message;
  }
  public void setMessage(Message message ){
    this.message=message;
  }
}
