
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ResponseRegisterAccount implements Serializable {
  private Boolean success;
  private Response response;
  private Integer pageSize;
  private Integer pageNumber;
  private Integer totalRecords;
  private ResponseRegisterAccount_savedContacts[] savedContacts;
  public Boolean isSuccess(){
    return this.success;
  }
  public void setSuccess(Boolean success ){
    this.success=success;
  }
  public Response responseInstance(){
	if(this.response==null){
	this.response=new Response();
	}
	return this.response;
  }
  public Response getResponse(){
    return this.response;
  }
  public void setResponse(Response response ){
    this.response=response;
  }
  public Integer getPageSize(){
    return this.pageSize;
  }
  public void setPageSize(Integer pageSize ){
    this.pageSize=pageSize;
  }
  public Integer getPageNumber(){
    return this.pageNumber;
  }
  public void setPageNumber(Integer pageNumber ){
    this.pageNumber=pageNumber;
  }
  public Integer getTotalRecords(){
    return this.totalRecords;
  }
  public void setTotalRecords(Integer totalRecords ){
    this.totalRecords=totalRecords;
  }
  public ResponseRegisterAccount_savedContacts[] getSavedContacts(){
    return this.savedContacts;
  }
  public void setSavedContacts(ResponseRegisterAccount_savedContacts[] savedContacts ){
    this.savedContacts=savedContacts;
  }
}
