
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class ResponseGetColonyByMunicipality implements Serializable {
  private Boolean success;
  private AddressTypeItems[] addressTypeItems;
  private Message message;
  public Boolean isSuccess(){
    return this.success;
  }
  public void setSuccess(Boolean success ){
    this.success=success;
  }
  public AddressTypeItems[] getAddressTypeItems(){
    return this.addressTypeItems;
  }
  public void setAddressTypeItems(AddressTypeItems[] addressTypeItems ){
    this.addressTypeItems=addressTypeItems;
  }
  public Message messageInstance(){
	if(this.message==null){
	this.message=new Message();
	}
	return this.message;
  }
  public Message getMessage(){
    return this.message;
  }
  public void setMessage(Message message ){
    this.message=message;
  }
}
