
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class Reversal_processing implements Serializable {
  private String type;
  private String origin_account_type;
  private String destiny_account_type;
  private String code;
  public String getType(){
    return this.type;
  }
  public void setType(String type ){
    this.type=type;
  }
  public String getOrigin_account_type(){
    return this.origin_account_type;
  }
  public void setOrigin_account_type(String origin_account_type ){
    this.origin_account_type=origin_account_type;
  }
  public String getDestiny_account_type(){
    return this.destiny_account_type;
  }
  public void setDestiny_account_type(String destiny_account_type ){
    this.destiny_account_type=destiny_account_type;
  }
  public String getCode(){
    return this.code;
  }
  public void setCode(String code ){
    this.code=code;
  }
}
