
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class Reversal_installment_data implements Serializable {
  private String type_installments;
  private String number_of_installments;
  private String grace_period;
  public String getType_installments(){
    return this.type_installments;
  }
  public void setType_installments(String type_installments ){
    this.type_installments=type_installments;
  }
  public String getNumber_of_installments(){
    return this.number_of_installments;
  }
  public void setNumber_of_installments(String number_of_installments ){
    this.number_of_installments=number_of_installments;
  }
  public String getGrace_period(){
    return this.grace_period;
  }
  public void setGrace_period(String grace_period ){
    this.grace_period=grace_period;
  }
}
