
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class Tokens_62 implements Serializable {
  private java.math.BigDecimal affiliation_number;
  private java.math.BigDecimal store_number;
  private String pos_id;
  private String cashier;
  private String transaction;
  private String pinpad;
  public java.math.BigDecimal getAffiliation_number(){
    return this.affiliation_number;
  }
  public void setAffiliation_number(java.math.BigDecimal affiliation_number ){
    this.affiliation_number=affiliation_number;
  }
  public java.math.BigDecimal getStore_number(){
    return this.store_number;
  }
  public void setStore_number(java.math.BigDecimal store_number ){
    this.store_number=store_number;
  }
  public String getPos_id(){
    return this.pos_id;
  }
  public void setPos_id(String pos_id ){
    this.pos_id=pos_id;
  }
  public String getCashier(){
    return this.cashier;
  }
  public void setCashier(String cashier ){
    this.cashier=cashier;
  }
  public String getTransaction(){
    return this.transaction;
  }
  public void setTransaction(String transaction ){
    this.transaction=transaction;
  }
  public String getPinpad(){
    return this.pinpad;
  }
  public void setPinpad(String pinpad ){
    this.pinpad=pinpad;
  }
}
