
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class TransactionIndicators implements Serializable {
  private Boolean cardPresent;
  private Boolean cardholderPresent;
  private Boolean cvv2Present;
  private Boolean pinValidatedOffline;
  public Boolean isCardPresent(){
    return this.cardPresent;
  }
  public void setCardPresent(Boolean cardPresent ){
    this.cardPresent=cardPresent;
  }
  public Boolean isCardholderPresent(){
    return this.cardholderPresent;
  }
  public void setCardholderPresent(Boolean cardholderPresent ){
    this.cardholderPresent=cardholderPresent;
  }
  public Boolean isCvv2Present(){
    return this.cvv2Present;
  }
  public void setCvv2Present(Boolean cvv2Present ){
    this.cvv2Present=cvv2Present;
  }
  public Boolean isPinValidatedOffline(){
    return this.pinValidatedOffline;
  }
  public void setPinValidatedOffline(Boolean pinValidatedOffline ){
    this.pinValidatedOffline=pinValidatedOffline;
  }
}
