
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class UpdateCustomerAddressRequest implements Serializable {
  private Integer externalCustomerId;
  private String country;
  private String zipcode;
  private String province;
  private String city;
  private String subdivisioncode;
  private String townCode;
  private String street;
  private String externalNumber;
  private String internalNumber;
  private String referenceAddress;
  private String timeCurrentReside;
  private String addressTypeCode;
  private String propertyTypeCode;
  public Integer getExternalCustomerId(){
    return this.externalCustomerId;
  }
  public void setExternalCustomerId(Integer externalCustomerId ){
    this.externalCustomerId=externalCustomerId;
  }
  public String getCountry(){
    return this.country;
  }
  public void setCountry(String country ){
    this.country=country;
  }
  public String getZipcode(){
    return this.zipcode;
  }
  public void setZipcode(String zipcode ){
    this.zipcode=zipcode;
  }
  public String getProvince(){
    return this.province;
  }
  public void setProvince(String province ){
    this.province=province;
  }
  public String getCity(){
    return this.city;
  }
  public void setCity(String city ){
    this.city=city;
  }
  public String getSubdivisioncode(){
    return this.subdivisioncode;
  }
  public void setSubdivisioncode(String subdivisioncode ){
    this.subdivisioncode=subdivisioncode;
  }
  public String getTownCode(){
    return this.townCode;
  }
  public void setTownCode(String townCode ){
    this.townCode=townCode;
  }
  public String getStreet(){
    return this.street;
  }
  public void setStreet(String street ){
    this.street=street;
  }
  public String getExternalNumber(){
    return this.externalNumber;
  }
  public void setExternalNumber(String externalNumber ){
    this.externalNumber=externalNumber;
  }
  public String getInternalNumber(){
    return this.internalNumber;
  }
  public void setInternalNumber(String internalNumber ){
    this.internalNumber=internalNumber;
  }
  public String getReferenceAddress(){
    return this.referenceAddress;
  }
  public void setReferenceAddress(String referenceAddress ){
    this.referenceAddress=referenceAddress;
  }
  public String getTimeCurrentReside(){
    return this.timeCurrentReside;
  }
  public void setTimeCurrentReside(String timeCurrentReside ){
    this.timeCurrentReside=timeCurrentReside;
  }
  public String getAddressTypeCode(){
    return this.addressTypeCode;
  }
  public void setAddressTypeCode(String addressTypeCode ){
    this.addressTypeCode=addressTypeCode;
  }
  public String getPropertyTypeCode(){
    return this.propertyTypeCode;
  }
  public void setPropertyTypeCode(String propertyTypeCode ){
    this.propertyTypeCode=propertyTypeCode;
  }
}
