
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class VirtualCard implements Serializable {
  private String cardId;
  private String debitCardNumber;
  private String debitCardState;
  public String getCardId(){
    return this.cardId;
  }
  public void setCardId(String cardId ){
    this.cardId=cardId;
  }
  public String getDebitCardNumber(){
    return this.debitCardNumber;
  }
  public void setDebitCardNumber(String debitCardNumber ){
    this.debitCardNumber=debitCardNumber;
  }
  public String getDebitCardState(){
    return this.debitCardState;
  }
  public void setDebitCardState(String debitCardState ){
    this.debitCardState=debitCardState;
  }
}
