
    /************************************************************/
    /*                     IMPORTANTE                           */
    /*   Esta aplicacion es parte de los  paquetes bancarios    */
    /*   propiedad de COBISCORP.                                */
    /*   Su uso no autorizado queda  expresamente  prohibido    */
    /*   asi como cualquier alteracion o agregado hecho  por    */
    /*   alguno de sus usuarios sin el debido consentimiento    */
    /*   por escrito de COBISCORP.                              */
    /*   Este programa esta protegido por la ley de derechos    */
    /*   de autor  y por las convenciones internacionales de    */
    /*   propiedad intelectual.   Su  uso no autorizado dara    */
    /*   derecho  a   COBISCORP   para  obtener  ordenes  de    */
    /*   secuestro o retencion  y  para perseguir penalmente    */
    /*   a los autores de cualquier infraccion.                 */
    /************************************************************/
    /*   This code was generated by CEN-SG.                     */
    /*   Changes to this file may cause incorrect behavior      */
    /*   and will be lost if the code is regenerated.           */
    /************************************************************/

    package cobiscorp.ecobis.datacontractoperations.dto;
import java.util.ArrayList;

import java.io.Serializable;

import java.util.HashMap;


public class WithdrawalDock_exchange_rate implements Serializable {
  private String dest_asset_code;
  private String date_time_gmt;
  private String final_billing_value;
  public String getDest_asset_code(){
    return this.dest_asset_code;
  }
  public void setDest_asset_code(String dest_asset_code ){
    this.dest_asset_code=dest_asset_code;
  }
  public String getDate_time_gmt(){
    return this.date_time_gmt;
  }
  public void setDate_time_gmt(String date_time_gmt ){
    this.date_time_gmt=date_time_gmt;
  }
  public String getFinal_billing_value(){
    return this.final_billing_value;
  }
  public void setFinal_billing_value(String final_billing_value ){
    this.final_billing_value=final_billing_value;
  }
}
